// scripts/tauri/gen-frontend-routes.ts
// Codegen: walks frontend/src/app/api/**/route.ts and emits
// src/desktop/generated-frontend-routes.ts — a static route table the sidecar's
// frontend-route-mount dispatches against.
//
// Exclusions (proxies to :9420 / already owned by the backend sidecar):
//   - setup/*  -> backend setup-router.ts serves /api/setup/* directly
//   - health   -> backend serves /health + /readyz; the SDK hits /api ?? no alias
//                 ... actually /api/health is the SDK's own route; see README.
//
// Regenerate: bun run scripts/tauri/gen-frontend-routes.ts
// (compile-sidecar.ts runs this automatically before bundling).

import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join, relative, sep } from 'node:path'

const repoRoot = join(import.meta.dir, '..', '..')
const apiRoot = join(repoRoot, 'frontend', 'src', 'app', 'api')
const outFile = join(repoRoot, 'src', 'desktop', 'generated-frontend-routes.ts')

// Raw hint keys use forward slashes without the 'route.ts' suffix
const EXCLUDED = new Set([
  'setup/complete',
  'setup/kill',
  'setup/launch-visible',
  'setup/profiles',
  'setup/verify',
  'setup/workspace',
  'health',
  '',
])

interface RouteSeg {
  hint: string // relative key, slash-joined, e.g. 'agent/canvas/command'
  methods: string[]
}

export function collectFrontendRoutes(): RouteSeg[] {
  const out: RouteSeg[] = []
  const walk = (dir: string, prefix: string) => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name)
      if (statSync(p).isDirectory()) {
        walk(p, `${prefix}${name}/`)
        continue
      }
      if (name !== 'route.ts') continue
      // prefix uses forward slashes (joins use '/'); split on '/' only
      const hint = `${prefix}route.ts`
        .split('/')
        .filter(Boolean)
        .slice(0, -1)
        .join('/')
      if (EXCLUDED.has(hint) || hint === '') continue
      const src = readFileSync(p, 'utf8')
      const methods = [
        ...src.matchAll(/export\s+(?:async\s+)?function\s+(GET|POST|PUT|PATCH|DELETE)\s*\(/g),
      ].map((m) => m[1])
      if (methods.length === 0) continue
      out.push({ hint, methods })
    }
  }
  walk(apiRoot, '')
  out.sort((a, b) => a.hint.localeCompare(b.hint))
  return out
}

export function generateFrontendRoutes(): string {
  const routes = collectFrontendRoutes()

  const importLines: string[] = []
  const entryLines: string[] = []
  routes.forEach((r, i) => {
    const absRoute = join(apiRoot, ...r.hint.split('/'), 'route.ts')
    const impRel = relative(dirname(outFile), absRoute).split(sep).join('/')
    const alias = `_m${i}`
    importLines.push(`import * as ${alias} from ${JSON.stringify(impRel)}`)
    const handlers = r.methods
      .map(
        (m) =>
          `    ${m}: (req: Request, params: Record<string, string>) => ${alias}.${m}?.(req, { params: Promise.resolve(params) }),`,
      )
      .join('\n')
    entryLines.push(`  {\n    path: ${JSON.stringify(`/api/${r.hint}`)},\n    handlers: {\n${handlers}\n    },\n  }`)
  })

  return `// @generated by scripts/tauri/gen-frontend-routes.ts — DO NOT EDIT.
// Route table for the desktop sidecar. Regenerate with
//   bun run gen:frontend-routes
// or via compile-sidecar before bundling.

/* eslint-disable */

${importLines.join('\n')}

export interface FrontendHandler {
  (req: Request, params: Record<string, string>): unknown
}

export interface FrontendRouteEntry {
  path: string
  handlers: Partial<Record<'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE', FrontendHandler>>
}

export const frontendRoutes: FrontendRouteEntry[] = [
${entryLines.join(',\n')}
]
`
}

if (import.meta.main) {
  const gen = generateFrontendRoutes()
  mkdirSync(dirname(outFile), { recursive: true })
  writeFileSync(outFile, gen)
  const count = (gen.match(/    path: "/g) ?? []).length
  console.log(`[gen] wrote ${outFile}`)
  console.log(`[gen] ${count} frontend routes ported`)
}