// AUTO-GENERATED from seeds/providers/*.json — canonical in-repo provider manifests.
// Replaces on-disk JSON so seeding performs zero filesystem reads at boot.
// Type-checked at runtime via ProviderManifestSchema.safeParse() in the seed script.
// Typed loosely here because JSON manifests omit optional fields the Zod schema defaults.
export const PROVIDER_MANIFESTS: unknown[] = [
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'chatgpt',
      display_name: 'ChatGPT',
      description: "OpenAI's ChatGPT assistant",
      category: 'ai',
      provider_type: 'llm',
      website_url: 'https://chatgpt.com',
      documentation_url: 'https://platform.openai.com/docs',
      auth_type: 'browser',
      has_multi_account: true,
      profile_strategy: 'per_account',
      fleet_config: {
        port_range: [9252, 9280],
        extra_args: ['--no-first-run'],
      },
      capabilities: [
        'select_model',
        'send_message',
        'edit_message',
        'regenerate_response',
        'upload_file',
        'create_new_chat',
        'navigate_chat',
        'delete_chat',
        'rename_chat',
        'browse_with_bing',
      ],
    },
    endpoints: [
      {
        label: 'Landing',
        url: 'https://chatgpt.com',
        endpoint_type: 'landing',
        is_default: true,
      },
      {
        label: 'Chat',
        url: 'https://chatgpt.com',
        endpoint_type: 'chat',
        selector: {
          composer: '#prompt-textarea',
          send_button: "[data-testid='send-button']",
        },
        composer_type: 'textarea',
        send_method: 'both',
        content_editable: false,
      },
      {
        label: 'Login',
        url: 'https://chatgpt.com/auth/login',
        endpoint_type: 'login',
        selector: {
          email_input: "input[name='email']",
          continue_button: "button[type='submit']",
        },
      },
    ],
    models: [
      {
        slug: 'gpt-4o',
        display_name: 'GPT-4o',
        is_default: true,
        context_window: 128000,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_vision: true,
        supports_tools: true,
      },
      {
        slug: 'gpt-4o-mini',
        display_name: 'GPT-4o Mini',
        context_window: 128000,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_vision: true,
        supports_tools: true,
      },
      {
        slug: 'o3',
        display_name: 'o3',
        context_window: 200000,
        max_output_tokens: 100000,
        supports_streaming: true,
        supports_vision: true,
        supports_thinking: true,
        supports_tools: true,
      },
      {
        slug: 'o4-mini',
        display_name: 'o4-mini',
        context_window: 200000,
        max_output_tokens: 100000,
        supports_streaming: true,
        supports_vision: true,
        supports_thinking: true,
        supports_tools: true,
      },
    ],
    capabilities_config: [
      {
        global_capability_id: 'send_message',
        recovery_strategies: [
          {
            type: 'retry_selector',
          },
          {
            type: 'navigate_home',
          },
        ],
        ui_component_override: 'text_input',
        ui_label_override: 'Send to ChatGPT',
        ui_icon_override: 'arrow-up-circle',
        ui_position_override: 'composer',
        ui_priority_override: 'primary',
      },
      {
        global_capability_id: 'select_model',
        ui_component_override: 'dropdown_selector',
        ui_label_override: 'Select GPT Model',
        ui_icon_override: 'cpu',
        ui_position_override: 'header',
        ui_priority_override: 'primary',
      },
    ],
    config: [
      {
        key: 'base_url',
        value: 'https://chatgpt.com',
      },
      {
        key: 'auth_type',
        value: 'email',
      },
    ],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'claude',
      display_name: 'Claude',
      description: "Anthropic's Claude AI assistant",
      category: 'ai',
      provider_type: 'llm',
      website_url: 'https://claude.ai',
      documentation_url: 'https://docs.anthropic.com',
      auth_type: 'browser',
      has_multi_account: true,
      profile_strategy: 'per_account',
      fleet_config: {
        port_range: [9222, 9250],
        extra_args: ['--disable-features=Translate', '--no-first-run'],
      },
      capabilities: [
        'select_model',
        'send_message',
        'edit_message',
        'regenerate_response',
        'toggle_extended_thinking',
        'upload_file',
        'create_new_chat',
        'navigate_chat',
        'delete_chat',
        'rename_chat',
        'deep_research',
      ],
    },
    endpoints: [
      {
        label: 'Landing',
        url: 'https://claude.ai',
        endpoint_type: 'landing',
        is_default: true,
      },
      {
        label: 'Chat',
        url: 'https://claude.ai/chat',
        endpoint_type: 'chat',
        selector: {
          composer:
            'div[contenteditable="true"].ProseMirror,div[contenteditable="true"][data-placeholder]',
          send_button: "[aria-label='Send Message'],[aria-label='Send message']",
        },
        composer_type: 'prosemirror',
        send_method: 'both',
        content_editable: true,
      },
      {
        label: 'Login',
        url: 'https://claude.ai/login',
        endpoint_type: 'login',
        selector: {
          email_input: "input[type='email']",
          continue_button: "button[type='submit']",
        },
      },
    ],
    models: [
      {
        slug: 'claude-sonnet-4-20250514',
        display_name: 'Sonnet 4',
        is_default: true,
        context_window: 200000,
        max_output_tokens: 64000,
        supports_streaming: true,
        supports_vision: true,
        supports_thinking: true,
        supports_tools: true,
      },
      {
        slug: 'claude-opus-4-20250514',
        display_name: 'Opus 4',
        context_window: 200000,
        max_output_tokens: 64000,
        supports_streaming: true,
        supports_vision: true,
        supports_thinking: true,
        supports_tools: true,
      },
      {
        slug: 'claude-haiku-4-20250514',
        display_name: 'Haiku 4',
        context_window: 200000,
        max_output_tokens: 64000,
        supports_streaming: true,
        supports_vision: true,
        supports_tools: true,
      },
    ],
    capabilities_config: [
      {
        global_capability_id: 'send_message',
        recovery_strategies: [
          {
            type: 'retry_selector',
          },
          {
            type: 'retry_with_fallback',
            config: {
              fallback_selector: 'textarea',
            },
          },
          {
            type: 'navigate_home',
          },
        ],
        ui_component_override: 'text_input',
        ui_label_override: 'Send to Claude',
        ui_icon_override: 'arrow-up-circle',
        ui_position_override: 'composer',
        ui_priority_override: 'primary',
      },
      {
        global_capability_id: 'select_model',
        ui_component_override: 'dropdown_selector',
        ui_label_override: 'Select Claude Model',
        ui_icon_override: 'cpu',
        ui_position_override: 'header',
        ui_priority_override: 'primary',
      },
      {
        global_capability_id: 'toggle_extended_thinking',
        ui_component_override: 'toggle_switch',
        ui_label_override: 'Extended Thinking',
        ui_position_override: 'header',
        ui_priority_override: 'secondary',
        existential_rule_override: 'message_has_thinking_block',
      },
      {
        global_capability_id: 'deep_research',
        ui_component_override: 'action_button',
        ui_label_override: 'Deep Research',
        ui_icon_override: 'flask',
        ui_position_override: 'composer',
        ui_priority_override: 'secondary',
        min_plan_tier_override: 'pro',
      },
    ],
    config: [
      {
        key: 'base_url',
        value: 'https://claude.ai',
      },
      {
        key: 'auth_type',
        value: 'email',
      },
    ],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'deepseek',
      display_name: 'DeepSeek',
      description: 'DeepSeek AI assistant with strong coding and reasoning capabilities',
      category: 'ai',
      provider_type: 'llm',
      website_url: 'https://chat.deepseek.com',
      documentation_url: 'https://platform.deepseek.com/api-docs',
      auth_type: 'browser',
      has_multi_account: false,
      profile_strategy: 'per_account',
      fleet_config: {
        port_range: [9312, 9340],
      },
      capabilities: [
        'send_message',
        'edit_message',
        'regenerate_response',
        'create_new_chat',
        'navigate_chat',
        'delete_chat',
        'rename_chat',
      ],
    },
    endpoints: [
      {
        label: 'Landing',
        url: 'https://chat.deepseek.com',
        endpoint_type: 'landing',
        is_default: true,
      },
      {
        label: 'Chat',
        url: 'https://chat.deepseek.com',
        endpoint_type: 'chat',
        selector: {
          composer: 'textarea',
          send_button: "button[aria-label='Send']",
        },
        composer_type: 'textarea',
        send_method: 'both',
        content_editable: false,
      },
      {
        label: 'Login',
        url: 'https://chat.deepseek.com/sign_in',
        endpoint_type: 'login',
        selector: {
          email_input: "input[type='email']",
          continue_button: "button[type='submit']",
        },
      },
    ],
    models: [
      {
        slug: 'deepseek-chat',
        display_name: 'DeepSeek Chat (V3)',
        is_default: true,
        context_window: 65536,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
      },
      {
        slug: 'deepseek-reasoner',
        display_name: 'DeepSeek Reasoner (R1)',
        context_window: 65536,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_thinking: true,
      },
    ],
    capabilities_config: [
      {
        global_capability_id: 'send_message',
        recovery_strategies: [
          {
            type: 'retry_selector',
          },
          {
            type: 'navigate_home',
          },
        ],
        ui_component_override: 'text_input',
        ui_label_override: 'Send to DeepSeek',
        ui_icon_override: 'arrow-up-circle',
        ui_position_override: 'composer',
        ui_priority_override: 'primary',
      },
    ],
    config: [
      {
        key: 'base_url',
        value: 'https://chat.deepseek.com',
      },
      {
        key: 'auth_type',
        value: 'email',
      },
    ],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'facebook',
      display_name: 'Facebook Messenger',
      description: 'Facebook Messenger channel',
      category: 'messaging',
      provider_type: 'messaging',
      website_url: 'https://www.facebook.com/messages',
      auth_type: 'browser',
      has_multi_account: false,
      profile_strategy: 'single',
      fleet_config: {
        port_range: [9360, 9380],
        extra_args: ['--no-first-run'],
      },
      capabilities: ['channel_add', 'channel_connect', 'message_send', 'message_receive'],
    },
    endpoints: [
      {
        label: 'Web',
        url: 'https://www.facebook.com/messages',
        endpoint_type: 'landing',
        is_default: true,
      },
    ],
    models: [],
    capabilities_config: [],
    config: [
      {
        key: 'poll_strategy',
        value: 'cdp-scrape',
      },
    ],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'gemini',
      display_name: 'Gemini',
      description: "Google's Gemini AI assistant",
      category: 'ai',
      provider_type: 'llm',
      website_url: 'https://gemini.google.com',
      documentation_url: 'https://ai.google.dev/docs',
      auth_type: 'browser',
      has_multi_account: true,
      profile_strategy: 'per_account',
      fleet_config: {
        port_range: [9282, 9310],
        extra_args: ['--no-first-run'],
      },
      capabilities: [
        'select_model',
        'send_message',
        'edit_message',
        'regenerate_response',
        'upload_file',
        'create_new_chat',
        'navigate_chat',
        'delete_chat',
        'rename_chat',
      ],
    },
    endpoints: [
      {
        label: 'Landing',
        url: 'https://gemini.google.com',
        endpoint_type: 'landing',
        is_default: true,
      },
      {
        label: 'Chat',
        url: 'https://gemini.google.com/app',
        endpoint_type: 'chat',
        selector: {
          composer: '.ql-editor[contenteditable="true"]',
          send_button: "button[aria-label='Send message']",
        },
        composer_type: 'quill',
        send_method: 'click',
        content_editable: true,
      },
      {
        label: 'Login',
        url: 'https://accounts.google.com',
        endpoint_type: 'login',
      },
    ],
    models: [
      {
        slug: 'gemini-2.5-pro',
        display_name: 'Gemini 2.5 Pro',
        is_default: true,
        context_window: 1048576,
        max_output_tokens: 65536,
        supports_streaming: true,
        supports_vision: true,
        supports_thinking: true,
        supports_tools: true,
      },
      {
        slug: 'gemini-2.5-flash',
        display_name: 'Gemini 2.5 Flash',
        context_window: 1048576,
        max_output_tokens: 65536,
        supports_streaming: true,
        supports_vision: true,
        supports_thinking: true,
        supports_tools: true,
      },
      {
        slug: 'gemini-2.0-flash',
        display_name: 'Gemini 2.0 Flash',
        context_window: 1048576,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_vision: true,
        supports_tools: true,
      },
    ],
    capabilities_config: [
      {
        global_capability_id: 'send_message',
        recovery_strategies: [
          {
            type: 'retry_selector',
          },
          {
            type: 'navigate_home',
          },
        ],
        ui_component_override: 'text_input',
        ui_label_override: 'Send to Gemini',
        ui_icon_override: 'arrow-up-circle',
        ui_position_override: 'composer',
        ui_priority_override: 'primary',
      },
      {
        global_capability_id: 'select_model',
        ui_component_override: 'dropdown_selector',
        ui_label_override: 'Select Gemini Model',
        ui_icon_override: 'cpu',
        ui_position_override: 'header',
        ui_priority_override: 'primary',
      },
    ],
    config: [
      {
        key: 'base_url',
        value: 'https://gemini.google.com',
      },
      {
        key: 'auth_type',
        value: 'google',
      },
    ],
  },
  {
    provider: {
      slug: 'generic',
      display_name: 'Generic',
      description: 'Format-agnostic fallback provider for the parser chain',
      category: 'system',
      provider_type: 'system',
      website_url: 'https://cap-store.local',
      auth_type: 'none',
      has_multi_account: false,
      profile_strategy: 'none',
      fleet_config: {},
      capabilities: [],
    },
    endpoints: [],
    models: [],
    capabilities_config: [],
    config: [],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'qwen',
      display_name: 'Qwen',
      description: "Alibaba's Qwen AI assistant",
      category: 'ai',
      provider_type: 'llm',
      website_url: 'https://tongyi.aliyun.com',
      documentation_url: 'https://help.aliyun.com/zh/model-studio/',
      auth_type: 'browser',
      has_multi_account: false,
      profile_strategy: 'per_account',
      fleet_config: {
        port_range: [9372, 9400],
      },
      capabilities: ['send_message', 'select_model', 'create_new_chat', 'navigate_chat'],
    },
    endpoints: [
      {
        label: 'Landing',
        url: 'https://tongyi.aliyun.com',
        endpoint_type: 'landing',
        is_default: true,
      },
      {
        label: 'Chat',
        url: 'https://tongyi.aliyun.com/qianwen',
        endpoint_type: 'chat',
        selector: {
          composer: 'textarea',
          send_button: "button[aria-label='Send']",
        },
        composer_type: 'textarea',
        send_method: 'both',
        content_editable: false,
      },
    ],
    models: [
      {
        slug: 'qwen-max',
        display_name: 'Qwen Max',
        is_default: true,
        context_window: 32768,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
      },
      {
        slug: 'qwen-plus',
        display_name: 'Qwen Plus',
        context_window: 131072,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
      },
      {
        slug: 'qwen-turbo',
        display_name: 'Qwen Turbo',
        context_window: 131072,
        max_output_tokens: 8192,
        supports_streaming: true,
      },
    ],
    capabilities_config: [
      {
        global_capability_id: 'send_message',
        recovery_strategies: [
          {
            type: 'retry_selector',
          },
          {
            type: 'navigate_home',
          },
        ],
        ui_component_override: 'text_input',
        ui_label_override: 'Send to Qwen',
        ui_icon_override: 'arrow-up-circle',
        ui_position_override: 'composer',
        ui_priority_override: 'primary',
      },
      {
        global_capability_id: 'select_model',
        ui_component_override: 'dropdown_selector',
        ui_label_override: 'Select Qwen Model',
        ui_icon_override: 'cpu',
        ui_position_override: 'header',
        ui_priority_override: 'primary',
      },
    ],
    config: [
      {
        key: 'base_url',
        value: 'https://tongyi.aliyun.com',
      },
      {
        key: 'auth_type',
        value: 'email',
      },
    ],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'slack',
      display_name: 'Slack',
      description: 'Slack messaging channel',
      category: 'messaging',
      provider_type: 'messaging',
      website_url: 'https://api.slack.com',
      auth_type: 'oauth',
      has_multi_account: false,
      profile_strategy: 'single',
      fleet_config: {
        port_range: [9400, 9420],
        extra_args: [],
      },
      capabilities: ['channel_add', 'channel_connect', 'message_send', 'message_receive'],
    },
    endpoints: [
      {
        label: 'API',
        url: 'https://slack.com/api',
        endpoint_type: 'landing',
        is_default: true,
      },
    ],
    models: [],
    capabilities_config: [],
    config: [
      {
        key: 'poll_strategy',
        value: 'webhook',
      },
    ],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'studio-ai',
      display_name: 'Studio AI',
      description: 'Google AI Studio — Gemini API playground and prototyping environment',
      category: 'ai',
      provider_type: 'llm',
      website_url: 'https://aistudio.google.com',
      documentation_url: 'https://ai.google.dev/docs',
      auth_type: 'browser',
      has_multi_account: false,
      profile_strategy: 'per_account',
      fleet_config: {
        port_range: [9342, 9370],
      },
      capabilities: ['send_message', 'select_model', 'create_new_chat', 'navigate_chat'],
    },
    endpoints: [
      {
        label: 'Landing',
        url: 'https://aistudio.google.com',
        endpoint_type: 'landing',
        is_default: true,
      },
      {
        label: 'Chat',
        url: 'https://aistudio.google.com/prompts/new_chat',
        endpoint_type: 'chat',
        selector: {
          composer: 'rich-textarea',
          send_button: "button[aria-label='Send message']",
        },
        composer_type: 'textarea',
        send_method: 'both',
        content_editable: false,
      },
    ],
    models: [
      {
        slug: 'gemini-2.5-pro-preview',
        display_name: 'Gemini 2.5 Pro Preview',
        is_default: true,
        context_window: 1048576,
        max_output_tokens: 65536,
        supports_streaming: true,
        supports_vision: true,
        supports_thinking: true,
        supports_tools: true,
      },
      {
        slug: 'gemini-2.5-flash-preview',
        display_name: 'Gemini 2.5 Flash Preview',
        context_window: 1048576,
        max_output_tokens: 65536,
        supports_streaming: true,
        supports_vision: true,
        supports_tools: true,
      },
    ],
    capabilities_config: [
      {
        global_capability_id: 'send_message',
        recovery_strategies: [
          {
            type: 'retry_selector',
          },
          {
            type: 'navigate_home',
          },
        ],
        ui_component_override: 'text_input',
        ui_label_override: 'Send to Studio AI',
        ui_icon_override: 'arrow-up-circle',
        ui_position_override: 'composer',
        ui_priority_override: 'primary',
      },
      {
        global_capability_id: 'select_model',
        ui_component_override: 'dropdown_selector',
        ui_label_override: 'Select Model',
        ui_icon_override: 'cpu',
        ui_position_override: 'header',
        ui_priority_override: 'primary',
      },
    ],
    config: [
      {
        key: 'base_url',
        value: 'https://aistudio.google.com',
      },
      {
        key: 'auth_type',
        value: 'google',
      },
    ],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'system',
      display_name: 'System',
      description: 'System-level fallback parsers — universal fallback chain',
      category: 'system',
      provider_type: 'system',
      website_url: 'https://vivim.app',
      auth_type: 'none',
      has_multi_account: false,
      profile_strategy: 'shared',
      capabilities: [],
    },
    endpoints: [],
    models: [],
    capabilities_config: [],
    config: [],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'telegram',
      display_name: 'Telegram',
      description: 'Telegram messaging channel',
      category: 'messaging',
      provider_type: 'messaging',
      website_url: 'https://core.telegram.org',
      auth_type: 'api_key',
      has_multi_account: false,
      profile_strategy: 'single',
      fleet_config: {
        port_range: [9380, 9400],
        extra_args: [],
      },
      capabilities: ['channel_add', 'channel_connect', 'message_send', 'message_receive'],
    },
    endpoints: [
      {
        label: 'Bot API',
        url: 'https://api.telegram.org',
        endpoint_type: 'landing',
        is_default: true,
      },
    ],
    models: [],
    capabilities_config: [],
    config: [
      {
        key: 'poll_strategy',
        value: 'polling',
      },
    ],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'whatsapp',
      display_name: 'WhatsApp',
      description: 'WhatsApp Web messaging channel',
      category: 'messaging',
      provider_type: 'messaging',
      website_url: 'https://web.whatsapp.com',
      auth_type: 'browser',
      has_multi_account: false,
      profile_strategy: 'single',
      fleet_config: {
        port_range: [9340, 9360],
        extra_args: ['--no-first-run'],
      },
      capabilities: ['channel_add', 'channel_connect', 'message_send', 'message_receive'],
    },
    endpoints: [
      {
        label: 'Web',
        url: 'https://web.whatsapp.com',
        endpoint_type: 'landing',
        is_default: true,
      },
    ],
    models: [],
    capabilities_config: [],
    config: [
      {
        key: 'poll_strategy',
        value: 'cdp-scrape',
      },
    ],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'z-ai',
      display_name: 'Z AI',
      description: "Z.AI — Z.ai's multimodal AI assistant",
      category: 'ai',
      provider_type: 'llm',
      website_url: 'https://z.ai',
      auth_type: 'api',
      has_multi_account: false,
      profile_strategy: 'shared',
      capabilities: ['send_message', 'select_model'],
    },
    endpoints: [
      {
        label: 'API',
        url: 'https://api.z.ai/v1',
        endpoint_type: 'api',
        is_default: true,
        composer_type: 'textarea',
        send_method: 'both',
        content_editable: false,
      },
    ],
    models: [
      {
        slug: 'z-ai-default',
        display_name: 'Z AI Default',
        is_default: true,
        context_window: 128000,
        max_output_tokens: 4096,
        supports_streaming: true,
      },
    ],
    capabilities_config: [
      {
        global_capability_id: 'send_message',
        recovery_strategies: [
          {
            type: 'retry_selector',
          },
        ],
        ui_component_override: 'text_input',
        ui_label_override: 'Send to Z AI',
        ui_icon_override: 'arrow-up-circle',
        ui_position_override: 'composer',
        ui_priority_override: 'primary',
      },
    ],
    config: [
      {
        key: 'base_url',
        value: 'https://api.z.ai/v1',
      },
      {
        key: 'auth_type',
        value: 'api_key',
      },
    ],
  },
  {
    $schema: 'https://vivim.app/cap-store/v1/provider-manifest.schema.json',
    provider: {
      slug: 'opencode',
      display_name: 'OpenCode Local Agent',
      description:
        'Local agentic backbone powered by the opencode CLI. Runs one-shot agentic tasks with no API key using verified free models.',
      category: 'ai',
      provider_type: 'local-agent',
      website_url: 'https://opencode.ai',
      auth_type: 'none',
      has_multi_account: false,
      profile_strategy: 'single',
      capabilities: ['agent_run'],
    },
    endpoints: [
      {
        label: 'Local CLI',
        url: 'opencode://local',
        endpoint_type: 'api',
        is_default: true,
        composer_type: 'textarea',
        send_method: 'both',
        content_editable: false,
      },
    ],
    models: [
      {
        slug: 'qwen3.5-3b-free',
        display_name: 'Qwen 3.5 3B (free)',
        is_default: true,
        context_window: 131072,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
      },
      {
        slug: 'glm4.5-air-free',
        display_name: 'GLM 4.5 Air (free)',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
      },
      {
        slug: 'deepseek-v3.2-free',
        display_name: 'DeepSeek V3.2 (free)',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
      },
      {
        slug: 'grok4-fast-free',
        display_name: 'Grok 4 Fast (free)',
        context_window: 131072,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
      },
    ],
    capabilities_config: [
      {
        global_capability_id: 'agent_run',
        recovery_strategies: [{ type: 'retry_selector' }],
        ui_component_override: 'text_input',
        ui_label_override: 'Run agent task',
        ui_icon_override: 'terminal',
        ui_position_override: 'composer',
        ui_priority_override: 'primary',
      },
    ],
    config: [
      {
        key: 'transport',
        value: 'opencode-cli',
      },
      {
        key: 'run_mode',
        value: 'one-shot',
      },
    ],
  },
  // ── Grok (xAI) ────────────────────────────────────────────────────────────
  // Selectors are placeholders — the agent discovers these during exploration.
  {
    provider: {
      slug: 'grok',
      display_name: 'Grok',
      description: "xAI's Grok AI assistant",
      category: 'ai',
      provider_type: 'llm',
      website_url: 'https://x.com/i/grok',
      auth_type: 'browser',
      has_multi_account: false,
      profile_strategy: 'per_account',
      fleet_config: {
        port_range: [9412, 9440],
      },
      capabilities: [
        'send_message',
        'create_new_chat',
        'navigate_chat',
        'delete_chat',
      ],
    },
    endpoints: [
      {
        label: 'Landing',
        url: 'https://x.com/i/grok',
        endpoint_type: 'landing',
        is_default: true,
      },
      {
        label: 'Chat',
        url: 'https://x.com/i/grok',
        endpoint_type: 'chat',
        selector: {
          composer: '',
          send_button: '',
        },
        composer_type: 'textarea',
        send_method: 'both',
        content_editable: false,
      },
      {
        label: 'Login',
        url: 'https://x.com/i/flow/login',
        endpoint_type: 'login',
      },
    ],
    models: [
      {
        slug: 'grok-3',
        display_name: 'Grok 3',
        is_default: true,
        context_window: 131072,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
      },
      {
        slug: 'grok-3-mini',
        display_name: 'Grok 3 Mini',
        context_window: 131072,
        max_output_tokens: 8192,
        supports_streaming: true,
      },
    ],
    capabilities_config: [
      {
        global_capability_id: 'send_message',
        recovery_strategies: [{ type: 'retry_selector' }, { type: 'navigate_home' }],
        ui_component_override: 'text_input',
        ui_label_override: 'Send to Grok',
        ui_icon_override: 'arrow-up-circle',
        ui_position_override: 'composer',
        ui_priority_override: 'primary',
      },
    ],
    config: [
      { key: 'base_url', value: 'https://x.com' },
      { key: 'auth_type', value: 'x.com' },
    ],
  },
  // ── Mistral (Le Chat) ─────────────────────────────────────────────────────
  // Selectors are placeholders — the agent discovers these during exploration.
  {
    provider: {
      slug: 'mistral',
      display_name: 'Mistral',
      description: "Mistral AI's Le Chat assistant",
      category: 'ai',
      provider_type: 'llm',
      website_url: 'https://chat.mistral.ai',
      auth_type: 'browser',
      has_multi_account: false,
      profile_strategy: 'per_account',
      fleet_config: {
        port_range: [9442, 9470],
      },
      capabilities: [
        'send_message',
        'select_model',
        'create_new_chat',
        'navigate_chat',
        'delete_chat',
      ],
    },
    endpoints: [
      {
        label: 'Landing',
        url: 'https://chat.mistral.ai',
        endpoint_type: 'landing',
        is_default: true,
      },
      {
        label: 'Chat',
        url: 'https://chat.mistral.ai/chat',
        endpoint_type: 'chat',
        selector: {
          composer: '',
          send_button: '',
        },
        composer_type: 'textarea',
        send_method: 'both',
        content_editable: false,
      },
    ],
    models: [
      {
        slug: 'mistral-large',
        display_name: 'Mistral Large',
        is_default: true,
        context_window: 131072,
        max_output_tokens: 32768,
        supports_streaming: true,
        supports_tools: true,
      },
      {
        slug: 'mistral-medium',
        display_name: 'Mistral Medium',
        context_window: 32768,
        max_output_tokens: 8192,
        supports_streaming: true,
      },
      {
        slug: 'codestral',
        display_name: 'Codestral',
        context_window: 32768,
        max_output_tokens: 8192,
        supports_streaming: true,
      },
    ],
    capabilities_config: [
      {
        global_capability_id: 'send_message',
        recovery_strategies: [{ type: 'retry_selector' }, { type: 'navigate_home' }],
        ui_component_override: 'text_input',
        ui_label_override: 'Send to Mistral',
        ui_icon_override: 'arrow-up-circle',
        ui_position_override: 'composer',
        ui_priority_override: 'primary',
      },
    ],
    config: [
      { key: 'base_url', value: 'https://chat.mistral.ai' },
      { key: 'auth_type', value: 'email' },
    ],
  },
]
