// devops/runtime-test/build-frontend.ts
// Unit 5.2 — Frontend Scaffold
//
// AGENT-SAFE: bounded, idempotent, no hanging I/O.
//
// Ensures the prod frontend (frontend) ships the contract-interpreter backbone from
// the `vivi-frontend` skill: the CapabilitySurface host + GenericCapabilityRenderer
// + ResultRenderer + ConfirmGate. Copies them from the skill templates only when
// absent, so re-running never clobbers bespoke work. Also appends the public
// `@ui` barrel exports once.

import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { readFile, writeFile, mkdir, copyFile, access } from 'node:fs/promises'

const HERE = dirname(fileURLToPath(import.meta.url))
// devops/runtime-test → repo root → .opencode/skill/vivi-frontend/templates
const SKILL_TEMPLATES = resolve(HERE, '../../.opencode/skill/vivi-frontend/templates')
const UI_ROOT = 'frontend'
const UI_SRC = resolve(UI_ROOT, 'src')

/** A renderer to register into the CapabilityRegistry ledger (U5 auto-register). */
export interface RendererReg {
  slug: string
  /** Best-practice note captured from sandbox iteration. */
  bestPracticeNote?: string
}

/**
 * Unit U5 — auto-register discovered renderers into the CapabilityRegistry ledger.
 * Idempotent: regenerates the whole generated file each run (never clobbers bespoke work
 * in index.ts). A registered slug tells the generic renderer / runtime that this
 * capability has a dedicated surface and a matching canvas layer (U4).
 */
export async function registerRenderers(renderers: RendererReg[]): Promise<void> {
  if (renderers.length === 0) return
  const lines = [
    "// AUTO-GENERATED by devops build-frontend — do not edit by hand.",
    "import { CapabilityRegistry } from './index.js'",
    '',
    ...renderers.map(
      (r) =>
        `CapabilityRegistry.register(${JSON.stringify(r.slug)}, { slug: ${JSON.stringify(
          r.slug,
        )}, bestPracticeNote: ${JSON.stringify(r.bestPracticeNote ?? 'auto-wired via vivi-frontend')} })`,
    ),
    '',
  ]
  await mkdir(UI_SRC, { recursive: true })
  await writeFile(resolve(UI_SRC, 'registry', 'auto-generated.ts'), lines.join('\n'), 'utf8')
}

/**
 * Emit a canvas-layer manifest consumed by the runtime loop (U4) to spawn the matching
 * atomic composable canvas layer for each wired capability. Pure data — no DB at build.
 */
export async function emitCanvasLayerManifest(slugs: string[]): Promise<void> {
  const manifest = {
    generatedAt: Date.now(),
    source: 'vivi-frontend',
    layers: slugs.map((slug) => ({ slug, layerSlug: `cap-layer-${slug}` })),
  }
  await mkdir(UI_ROOT, { recursive: true })
  await writeFile(
    resolve(UI_ROOT, 'canvas-layer-manifest.json'),
    JSON.stringify(manifest, null, 2),
    'utf8',
  )
}

// [template file, destination relative to frontend/src, kind]
const CORE_FILES: Array<[string, string]> = [
  ['capability-surface.tsx', 'features/capability-surface.tsx'],
  ['generic-renderer.tsx', 'components/generic-capability-renderer.tsx'],
  ['result-renderer.tsx', 'components/result-renderer.tsx'],
  ['confirm-gate.tsx', 'components/confirm-gate.tsx'],
]

const BARREL_EXPORTS = [
  "export { CapabilitySurface } from './features/capability-surface.js'",
  "export type { CapabilitySurfaceProps } from './features/capability-surface.js'",
  "export { GenericCapabilityRenderer } from './components/generic-capability-renderer.js'",
  "export type { ResolvedCapability } from './components/generic-capability-renderer.js'",
  "export { ResultRenderer } from './components/result-renderer.js'",
  "export type { RenderResult } from './components/result-renderer.js'",
  "export { ConfirmGate } from './components/confirm-gate.js'",
  "export { useResolvedCapabilities } from './sdk/use-resolved-capabilities.js'",
  "export type { ResolvedSlots, UseResolvedCapabilities } from './sdk/use-resolved-capabilities.js'",
]

async function exists(p: string): Promise<boolean> {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}

export interface ScaffoldFrontendOptions {
  /** Renderers to auto-register into the ledger (U5). */
  renderers?: RendererReg[]
  /** Slugs whose canvas layers the runtime should spawn (U4 manifest). */
  slugs?: string[]
}

export async function scaffoldFrontend(
  opts: ScaffoldFrontendOptions = {},
): Promise<{ ok: boolean; path: string; created: string[]; error?: string }> {
  const created: string[] = []
  try {
    await mkdir(UI_SRC, { recursive: true })

    for (const [tpl, dest] of CORE_FILES) {
      const target = resolve(UI_SRC, dest)
      if (await exists(target)) continue
      const src = resolve(SKILL_TEMPLATES, tpl)
      if (!(await exists(src))) {
        return { ok: false, path: UI_ROOT, created, error: `skill template missing: ${tpl}` }
      }
      await copyFile(src, target)
      created.push(dest)
    }

    // Idempotent barrel augmentation.
    const barrelPath = resolve(UI_SRC, 'index.ts')
    if (await exists(barrelPath)) {
      const current = await readFile(barrelPath, 'utf8')
      const missing = BARREL_EXPORTS.filter((line) => !current.includes(line))
      if (missing.length > 0) {
        await writeFile(barrelPath, `${current.replace(/\s*$/, '')}\n${missing.join('\n')}\n`, 'utf8')
        created.push('index.ts (barrel +exports)')
      }
    }

    // U5: auto-register renderers + emit canvas-layer manifest (idempotent).
    if (opts.renderers && opts.renderers.length > 0) {
      await registerRenderers(opts.renderers)
      created.push('registry/auto-generated.ts')
    }
    if (opts.slugs && opts.slugs.length > 0) {
      await emitCanvasLayerManifest(opts.slugs)
      created.push('canvas-layer-manifest.json')
    }

    return { ok: true, path: UI_ROOT, created }
  } catch (err) {
    return { ok: false, path: UI_ROOT, created, error: String(err) }
  }
}
