// devops/runtime-test/capability-codegen.ts
// Unit 1.3 — Capability codegen recipe.
//
// AGENT-SAFE: writes a single bounded file (no server, no DB). Replaces the old no-op
// `scaffoldBackend`. An autonomous agent can now emit a compilable `makeCapability`
// skeleton with the EXACT field shape (id/slug/name/description/category/inputSchema/
// outputSchema/cliCommand/ui/mcpToolName/apiEndpoint) instead of free-handing and
// drifting from cross-surface parity.

import { mkdirSync, writeFileSync } from 'node:fs'

export interface CodegenResult {
  ok: boolean
  path: string
  snippet: string
  error?: string
}

/**
 * Emit a `makeCapability` skeleton for `slug` into src/engines/generated/<slug>.ts.
 * Derives a `cap:<category>:<action>` id from the slug (conversation_rename -> cap:conversation:rename).
 */
export function scaffoldCapability(slug: string): CodegenResult {
  const clean = slug.replace(/[^a-z0-9_]/gi, '').toLowerCase()
  if (!clean) return { ok: false, path: '', snippet: '', error: 'invalid slug' }

  const parts = clean.split('_')
  const category = parts[0] || 'custom'
  const action = parts.slice(1).join('_') || 'action'
  const id = `cap:${category}:${action}`
  const name = action
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')

  const dir = 'src/engines/generated'
  const path = `${dir}/${clean}.ts`

  const snippet = `// GENERATED by: bun run devops runtime-test build backend --cap=${clean}
// Register this capability in src/engines/capability-bootstrap.ts inside
// registerDefaultCapabilities (add it to the \`defaults\` array). Then run
// \`bun run devops runtime-test catalog-gen\` to refresh the offline catalog.

import { makeCapability } from '../capability-bootstrap.js'
import type { BootstrapServices } from '../capability-bootstrap.js'

export function register${name.replace(/\W/g, '')}Capability(_services: BootstrapServices) {
  return makeCapability(
    {
      id: '${id}',
      slug: '${clean}',
      name: '${name}',
      description: 'TODO: describe ${name}.',
      category: '${category}',
      inputSchema: {
        type: 'object',
        properties: { /* TODO: inputs */ },
        required: [],
      },
      outputSchema: { type: 'object' },
      cliCommand: { name: '${category} ${action.replace(/_/g, ' ')}', aliases: ['${clean.slice(0, 4)}'], examples: [] },
      ui: { component: 'action-button', position: 'sidebar', order: 99 },
      mcpToolName: '${clean}',
      apiEndpoint: { method: 'POST', path: '/api/${category}/${action}' },
    },
    async (input) => {
      // TODO: implement handler using _services
      return { ok: true }
    },
  )
}
`

  try {
    mkdirSync(dir, { recursive: true })
    writeFileSync(path, snippet, 'utf8')
    return { ok: true, path, snippet }
  } catch (err) {
    return { ok: false, path, snippet, error: String(err) }
  }
}
