// devops/runtime-test/capability-codegen.ts
// Unit 1.3 — Capability codegen recipe.
//
// AGENT-SAFE: writes a single bounded file (no server, no DB). Replaces the old no-op
// `scaffoldBackend`. An autonomous agent can now emit a compilable `makeCapability`
// skeleton with the EXACT field shape (id/slug/name/description/category/inputSchema/
// outputSchema/cliCommand/ui/mcpToolName/apiEndpoint) instead of free-handing and
// drifting from cross-surface parity.

import { mkdirSync, writeFileSync, appendFileSync } from 'node:fs'

export interface CodegenResult {
  ok: boolean
  path: string
  snippet: string
  error?: string
}

const CATALOG_PATH = 'src/engines/nlcl/catalog.ts'

/**
 * Derive a `cap:<category>:<action>` id from the slug (conversation_rename -> cap:conversation:rename).
 */
export function deriveCapabilityId(slug: string): string {
  const clean = slug.replace(/[^a-z0-9_]/gi, '').toLowerCase()
  const parts = clean.split('_')
  const category = parts[0] || 'custom'
  const action = parts.slice(1).join('_') || 'action'
  return `cap:${category}:${action}`
}

/**
 * Emit a `makeCapability` skeleton for `slug` into src/engines/generated/<slug>.ts.
 * The generated file self-registers via `extendHandlerMap` on module load so it
 * participates in `registerGeneratedCapabilities` without hand-editing the handler map.
 */
export function scaffoldCapability(slug: string): CodegenResult {
  const clean = slug.replace(/[^a-z0-9_]/gi, '').toLowerCase()
  if (!clean) return { ok: false, path: '', snippet: '', error: 'invalid slug' }

  const parts = clean.split('_')
  const category = parts[0] || 'custom'
  const action = parts.slice(1).join('_') || 'action'
  const id = deriveCapabilityId(slug)
  const name = action
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
  const abbrev = parts.slice(0, 2).join('').slice(0, 4)
  const handlerSlug = `${category}_${action}`

  const dir = 'src/engines/generated'
  const path = `${dir}/${clean}.ts`

  const snippet = `// GENERATED by: bun run devops runtime-test build backend --cap=${clean}

import { makeCapability } from '../capability-bootstrap.js'
import type { BootstrapServices } from '../capability-bootstrap.js'
import { extendHandlerMap } from '../capability-bootstrap-generated.js'

export function register${name.replace(/\W/g, '')}Capability(_services: BootstrapServices) {
  return makeCapability(
    {
      id: '${id}',
      slug: '${handlerSlug}',
      name: '${name}',
      description: 'TODO: describe ${name}.',
      category: '${category}',
      inputSchema: {
        type: 'object',
        properties: { /* TODO: inputs */ },
        required: [],
      },
      outputSchema: { type: 'object' },
      cliCommand: { name: '${category} ${action.replace(/_/g, ' ')}', aliases: ['${abbrev}'], examples: ['${category} ${action.replace(/_/g, ' ')}'] },
      ui: { component: 'action-button', position: 'sidebar', order: 99 },
      mcpToolName: '${handlerSlug}',
      apiEndpoint: { method: 'POST', path: '/api/${category}/${action}' },
    },
    async (input) => {
      // TODO: implement handler using _services
      return { ok: true }
    },
  )
}

extendHandlerMap('${handlerSlug}', register${name.replace(/\W/g, '')}Capability)
`

  try {
    mkdirSync(dir, { recursive: true })
    writeFileSync(path, snippet, 'utf8')
    return { ok: true, path, snippet }
  } catch (err) {
    return { ok: false, path, snippet, error: String(err) }
  }
}

/**
 * Append an NL catalog entry to src/engines/nlcl/catalog.ts inside the
 * `conversationPatterns` array. Safe to call multiple times (idempotent-ish:
 * does not deduplicate, caller should check).
 */
export function scaffoldCatalogEntry(slug: string, capabilityId: string): CodegenResult {
  const clean = slug.replace(/[^a-z0-9_]/gi, '').toLowerCase()
  if (!clean) return { ok: false, path: '', snippet: '', error: 'invalid slug' }

  const parts = clean.split('_')
  const category = parts[0] || 'custom'
  const action = parts.slice(1).join('_') || 'action'
  const name = action
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')

  const patternEntry = `
  pattern('${category}.${action}', '${category}.${action}', '${name}', {
    patterns: [
      {
        regex: /(?:${category})\\s+(?:${action.replace(/_/g, ' ')})/i,
        priority: 10,
        keywords: ['${category}', '${action.replace(/_/g, ' ')}'],
        extract: () => ({}),
      },
    ],
    aliases: ['${clean}'],
    examples: ['${category} ${action.replace(/_/g, ' ')}'],
    inputSchema: { type: 'object' },
    executor: '${category}',
    category: '${category}',
    classification: 'action',
    capabilityId: '${capabilityId}',
    execute: async () => ({}),
  }),
`

  try {
    appendFileSync(CATALOG_PATH, patternEntry, 'utf8')
    return { ok: true, path: CATALOG_PATH, snippet: patternEntry }
  } catch (err) {
    return { ok: false, path: CATALOG_PATH, snippet: '', error: String(err) }
  }
}
