import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

type CommandDescriptionSeed = {
  commandId: string
  description: string
  patterns: string[]
  category: string
  prefix: string | null
  confidence: number
  enabled: boolean
}

const commandDescriptions: CommandDescriptionSeed[] = [
  // ── / Prefix: Conversation Commands ───────────────────────────────
  {
    commandId: '/new',
    description: 'Create a new conversation',
    patterns: ['new conversation', 'start conversation', 'begin chat', 'create chat', 'fresh chat'],
    category: 'conversation',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/switch',
    description: 'Switch to a different provider',
    patterns: ['switch to', 'use provider', 'change provider', 'swap provider', 'go to provider'],
    category: 'provider',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/list',
    description: 'List all conversations',
    patterns: [
      'list conversations',
      'show chats',
      'show conversations',
      'view chats',
      'my conversations',
    ],
    category: 'conversation',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/search',
    description: 'Search conversations by keyword',
    patterns: ['search conversations', 'find chat', 'look for conversation', 'search chat history'],
    category: 'conversation',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/send',
    description: 'Send a message to the active provider',
    patterns: ['send message', 'message provider', 'talk to', 'chat with'],
    category: 'conversation',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/draft',
    description: 'Draft a message without sending',
    patterns: ['draft message', 'compose message', 'write draft', 'prepare message'],
    category: 'conversation',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/save',
    description: 'Save the current conversation',
    patterns: ['save conversation', 'save chat', 'persist conversation', 'store chat'],
    category: 'conversation',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/review',
    description: 'Review the last response',
    patterns: ['review response', 'check response', 'review answer', 'look at response'],
    category: 'conversation',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/recall',
    description: 'Recall a previous message',
    patterns: ['recall message', 'bring back', 'get previous', 'show last message'],
    category: 'conversation',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/tag',
    description: 'Tag the current conversation',
    patterns: ['tag conversation', 'add tag', 'label chat', 'categorize conversation'],
    category: 'tag',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/export',
    description: 'Export conversation data',
    patterns: ['export conversation', 'download chat', 'save as file', 'export chat history'],
    category: 'file',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/open',
    description: 'Open a file or URL',
    patterns: ['open file', 'open url', 'load file', 'show file', 'open link'],
    category: 'file',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/screenshot',
    description: 'Take a screenshot',
    patterns: ['take screenshot', 'capture screen', 'snapshot', 'screen capture'],
    category: 'browser',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/health',
    description: 'Check system health status',
    patterns: [
      'health check',
      'system status',
      'check health',
      'is everything ok',
      'how are things',
    ],
    category: 'system',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/providers',
    description: 'List available providers',
    patterns: ['list providers', 'show providers', 'available providers', 'what providers'],
    category: 'provider',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/fleet',
    description: 'Show provider fleet status',
    patterns: ['fleet status', 'show fleet', 'provider fleet', 'all providers status'],
    category: 'provider',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/help',
    description: 'Show available commands',
    patterns: ['help', 'show commands', 'what can i do', 'commands list', 'available commands'],
    category: 'discovery',
    prefix: '/',
    confidence: 0.95,
    enabled: true,
  },
  {
    commandId: '/clear',
    description: 'Clear the current conversation',
    patterns: ['clear conversation', 'clear chat', 'reset conversation', 'start over'],
    category: 'conversation',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/focus',
    description: 'Focus on a specific topic',
    patterns: ['focus on', 'concentrate on', 'zoom in on', 'narrow down'],
    category: 'conversation',
    prefix: '/',
    confidence: 0.8,
    enabled: true,
  },
  {
    commandId: '/copy',
    description: 'Copy the last response',
    patterns: ['copy response', 'copy answer', 'copy that', 'copy to clipboard'],
    category: 'system',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/undo',
    description: 'Undo the last action',
    patterns: ['undo', 'undo last', 'reverse', 'go back'],
    category: 'system',
    prefix: '/',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '/automate',
    description: 'Create an automation workflow',
    patterns: ['automate', 'create automation', 'set up automation', 'build workflow'],
    category: 'automation',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/moments',
    description: 'View saved moments',
    patterns: ['moments', 'show moments', 'saved moments', 'view moments'],
    category: 'memory',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/opencode',
    description: 'Open the coding environment',
    patterns: ['open code', 'start coding', 'code mode', 'development mode'],
    category: 'system',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/session',
    description: 'Manage the current session',
    patterns: ['session info', 'show session', 'session details', 'current session'],
    category: 'session',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/newsletter',
    description: 'Create or manage newsletters',
    patterns: ['newsletter', 'create newsletter', 'send newsletter', 'manage newsletter'],
    category: 'email',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/schedule',
    description: 'Schedule a task',
    patterns: ['schedule', 'set schedule', 'create schedule', 'plan task'],
    category: 'automation',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/background',
    description: 'Run a task in the background',
    patterns: ['run in background', 'background task', 'async task', 'run later'],
    category: 'automation',
    prefix: '/',
    confidence: 0.8,
    enabled: true,
  },
  {
    commandId: '/theme',
    description: 'Change the UI theme',
    patterns: ['change theme', 'switch theme', 'dark mode', 'light mode', 'toggle theme'],
    category: 'system',
    prefix: '/',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '/layout',
    description: 'Change the UI layout',
    patterns: ['change layout', 'switch layout', 'layout options', 'ui layout'],
    category: 'system',
    prefix: '/',
    confidence: 0.8,
    enabled: true,
  },

  // ── @ Prefix: Provider Mention Commands ───────────────────────────
  {
    commandId: '@claude',
    description: 'Send message to Claude provider',
    patterns: ['talk to claude', 'ask claude', 'claude says', 'use claude', 'chat with claude'],
    category: 'provider',
    prefix: '@',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '@chatgpt',
    description: 'Send message to ChatGPT provider',
    patterns: [
      'talk to chatgpt',
      'ask chatgpt',
      'chatgpt says',
      'use chatgpt',
      'chat with chatgpt',
    ],
    category: 'provider',
    prefix: '@',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '@gemini',
    description: 'Send message to Gemini provider',
    patterns: ['talk to gemini', 'ask gemini', 'gemini says', 'use gemini', 'chat with gemini'],
    category: 'provider',
    prefix: '@',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '@deepseek',
    description: 'Send message to DeepSeek provider',
    patterns: ['talk to deepseek', 'ask deepseek', 'deepseek says', 'use deepseek'],
    category: 'provider',
    prefix: '@',
    confidence: 0.85,
    enabled: false,
  },
  {
    commandId: '@qwen',
    description: 'Send message to Qwen provider',
    patterns: ['talk to qwen', 'ask qwen', 'qwen says', 'use qwen'],
    category: 'provider',
    prefix: '@',
    confidence: 0.85,
    enabled: false,
  },
  {
    commandId: '@grok',
    description: 'Send message to Grok provider',
    patterns: ['talk to grok', 'ask grok', 'grok says', 'use grok'],
    category: 'provider',
    prefix: '@',
    confidence: 0.85,
    enabled: false,
  },

  // ── # Prefix: Tag Commands ────────────────────────────────────────
  {
    commandId: '#add',
    description: 'Add a tag to the current conversation',
    patterns: ['add tag', 'tag this', 'label this', 'categorize'],
    category: 'tag',
    prefix: '#',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '#list',
    description: 'List all tags',
    patterns: ['list tags', 'show tags', 'all tags', 'view tags'],
    category: 'tag',
    prefix: '#',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '#search',
    description: 'Search by tag',
    patterns: ['search by tag', 'find tag', 'filter by tag', 'tag search'],
    category: 'tag',
    prefix: '#',
    confidence: 0.85,
    enabled: true,
  },

  // ── ! Prefix: DevOps Commands ─────────────────────────────────────
  {
    commandId: '!health',
    description: 'Check system health',
    patterns: ['health check', 'system health', 'check status', 'is system ok'],
    category: 'system',
    prefix: '!',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '!fleet',
    description: 'Show provider fleet status',
    patterns: ['fleet status', 'provider fleet', 'all providers', 'fleet health'],
    category: 'provider',
    prefix: '!',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '!providers',
    description: 'List all providers',
    patterns: ['list providers', 'show providers', 'all providers', 'provider list'],
    category: 'provider',
    prefix: '!',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '!caps',
    description: 'List all capabilities',
    patterns: ['list capabilities', 'show capabilities', 'all capabilities', 'capability list'],
    category: 'automation',
    prefix: '!',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '!version',
    description: 'Show system version',
    patterns: ['version', 'show version', 'system version', 'what version'],
    category: 'system',
    prefix: '!',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '!workspace',
    description: 'Show workspace info',
    patterns: ['workspace info', 'show workspace', 'workspace status', 'current workspace'],
    category: 'system',
    prefix: '!',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '!trace-export',
    description: 'Export trace data',
    patterns: ['export trace', 'save trace', 'trace export', 'download trace'],
    category: 'system',
    prefix: '!',
    confidence: 0.8,
    enabled: true,
  },
  {
    commandId: '!trace-clear',
    description: 'Clear trace data',
    patterns: ['clear trace', 'reset trace', 'delete trace', 'trace clear'],
    category: 'system',
    prefix: '!',
    confidence: 0.8,
    enabled: true,
  },
  {
    commandId: '!config-export',
    description: 'Export configuration',
    patterns: ['export config', 'save config', 'config export', 'download config'],
    category: 'system',
    prefix: '!',
    confidence: 0.8,
    enabled: true,
  },
  {
    commandId: '!config-import',
    description: 'Import configuration',
    patterns: ['import config', 'load config', 'config import', 'upload config'],
    category: 'system',
    prefix: '!',
    confidence: 0.8,
    enabled: true,
  },
  {
    commandId: '!deploy',
    description: 'Deploy the application',
    patterns: ['deploy', 'deploy app', 'deploy system', 'push to production'],
    category: 'system',
    prefix: '!',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '!audit',
    description: 'Run code audit',
    patterns: ['run audit', 'code audit', 'audit code', 'check code quality'],
    category: 'system',
    prefix: '!',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '!gate',
    description: 'Run quality gate',
    patterns: ['run gate', 'quality gate', 'gate check', 'pass gate'],
    category: 'system',
    prefix: '!',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '!converge',
    description: 'Run convergence check',
    patterns: ['convergence check', 'check convergence', 'run convergence', 'converge'],
    category: 'system',
    prefix: '!',
    confidence: 0.8,
    enabled: true,
  },
  {
    commandId: '!invariants',
    description: 'Check system invariants',
    patterns: ['check invariants', 'invariant check', 'verify invariants', 'run invariants'],
    category: 'system',
    prefix: '!',
    confidence: 0.8,
    enabled: true,
  },

  // ── ~ Prefix: Context Reference Commands ──────────────────────────
  {
    commandId: '~last',
    description: 'Reference the last message',
    patterns: ['last message', 'previous message', 'that message', 'the last one'],
    category: 'conversation',
    prefix: '~',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '~this',
    description: 'Reference the current context',
    patterns: ['this context', 'current context', 'here', 'this one'],
    category: 'conversation',
    prefix: '~',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '~active',
    description: 'Reference the active provider',
    patterns: ['active provider', 'current provider', 'the active one', 'now'],
    category: 'provider',
    prefix: '~',
    confidence: 0.85,
    enabled: true,
  },

  // ── ? Prefix: Discovery Commands ──────────────────────────────────
  {
    commandId: '?help',
    description: 'Show help and available commands',
    patterns: ['help me', 'what can i do', 'show help', 'how to use'],
    category: 'discovery',
    prefix: '?',
    confidence: 0.95,
    enabled: true,
  },
  {
    commandId: '?providers',
    description: 'List available providers',
    patterns: ['what providers', 'available providers', 'which providers', 'provider options'],
    category: 'provider',
    prefix: '?',
    confidence: 0.9,
    enabled: true,
  },
  {
    commandId: '?tags',
    description: 'List available tags',
    patterns: ['what tags', 'available tags', 'which tags', 'tag options'],
    category: 'tag',
    prefix: '?',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '?recent',
    description: 'Show recent commands',
    patterns: ['recent commands', 'last commands', 'command history', 'what did i do'],
    category: 'system',
    prefix: '?',
    confidence: 0.85,
    enabled: true,
  },
  {
    commandId: '?search',
    description: 'Search for commands',
    patterns: ['find command', 'search commands', 'look for command', 'command search'],
    category: 'discovery',
    prefix: '?',
    confidence: 0.85,
    enabled: true,
  },

  // ── NLCL-style Natural Language Patterns ───────────────────────────
  {
    commandId: 'nlcl_switch_provider',
    description: 'Switch to a different AI provider',
    patterns: ['switch to', 'use provider', 'change to', 'swap to', 'go to provider'],
    category: 'provider',
    prefix: null,
    confidence: 0.8,
    enabled: true,
  },
  {
    commandId: 'nlcl_send_message',
    description: 'Send a message to the active provider',
    patterns: ['send message', 'tell', 'ask', 'say', 'write to'],
    category: 'conversation',
    prefix: null,
    confidence: 0.7,
    enabled: true,
  },
  {
    commandId: 'nlcl_create_conversation',
    description: 'Start a new conversation',
    patterns: ['new chat', 'start conversation', 'begin', 'fresh start'],
    category: 'conversation',
    prefix: null,
    confidence: 0.75,
    enabled: true,
  },
  {
    commandId: 'nlcl_health_check',
    description: 'Check if the system is working',
    patterns: ['are you ok', 'how are you', 'system ok', 'everything working'],
    category: 'system',
    prefix: null,
    confidence: 0.7,
    enabled: true,
  },
  {
    commandId: 'nlcl_open_file',
    description: 'Open a file in the editor',
    patterns: ['open file', 'show file', 'load file', 'display file'],
    category: 'file',
    prefix: null,
    confidence: 0.75,
    enabled: true,
  },
  {
    commandId: 'nlcl_search_conversations',
    description: 'Search through conversations',
    patterns: ['find conversation', 'search chat', 'look for', 'where is'],
    category: 'conversation',
    prefix: null,
    confidence: 0.7,
    enabled: true,
  },
  {
    commandId: 'nlcl_export_data',
    description: 'Export conversation or data',
    patterns: ['export', 'download', 'save as', 'get copy'],
    category: 'file',
    prefix: null,
    confidence: 0.7,
    enabled: true,
  },
  {
    commandId: 'nlcl_create_automation',
    description: 'Set up an automated workflow',
    patterns: ['automate', 'set up automation', 'create workflow', 'build automation'],
    category: 'automation',
    prefix: null,
    confidence: 0.75,
    enabled: true,
  },
  {
    commandId: 'nlcl_check_status',
    description: 'Check system or provider status',
    patterns: ['status', 'what is the status', 'check status', 'how is it going'],
    category: 'system',
    prefix: null,
    confidence: 0.7,
    enabled: true,
  },
  {
    commandId: 'nlcl_help',
    description: 'Get help with the system',
    patterns: ['help', 'what can you do', 'how do i', 'show me'],
    category: 'discovery',
    prefix: null,
    confidence: 0.7,
    enabled: true,
  },
]

async function seedCommandDescriptions() {
  // [audit] removed: console.log('Seeding command descriptions...')

  const now = BigInt(Date.now())

  for (const desc of commandDescriptions) {
    await prisma.commandDescription.upsert({
      where: { commandId: desc.commandId },
      create: {
        id: `cmd_${desc.commandId.replace(/[^a-z0-9]/gi, '_')}`,
        commandId: desc.commandId,
        description: desc.description,
        patterns: JSON.stringify(desc.patterns),
        category: desc.category,
        prefix: desc.prefix,
        confidence: desc.confidence,
        enabled: desc.enabled,
        createdAt: now,
        updatedAt: now,
      },
      update: {
        description: desc.description,
        patterns: JSON.stringify(desc.patterns),
        category: desc.category,
        prefix: desc.prefix,
        confidence: desc.confidence,
        enabled: desc.enabled,
        updatedAt: now,
      },
    })
  }

  const count = await prisma.commandDescription.count()
  // [audit] removed: console.log(`Seeded ${count} command descriptions`)
}

seedCommandDescriptions()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    // [audit] removed: console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
