// src/storage/impl/memory-intelligence-store-impl.ts
// Prisma-backed MemoryIntelligenceStore — CRUD for Phase 0 memory intelligence models.

import { newId } from '../../ids.js'
import type { CapStoreDb } from '../db.js'

// ── Domain types ────────────────────────────────────────────────────────────

export interface EntityRow {
  id: string
  name: string
  type: string
  description: string | null
  confidence: number
  mentionCount: number
  firstSeenAt: number
  lastSeenAt: number
  createdAt: number
  updatedAt: number
}

export interface EntityMentionRow {
  id: string
  entityId: string
  conversationId: string
  messageId: string
  context: string
  confidence: number
  ts: number
}

export interface DecisionRecordRow {
  id: string
  conversationId: string
  messageId: string
  decisionText: string
  rationale: string | null
  alternativesJson: string
  confidence: number
  ts: number
}

export interface PatternExtractRow {
  id: string
  name: string
  description: string
  patternType: string
  occurrences: number
  confidence: number
  firstSeenAt: number
  lastSeenAt: number
  createdAt: number
  updatedAt: number
}

export interface TopicRow {
  id: string
  name: string
  description: string | null
  color: string | null
  conversationCount: number
  createdAt: number
  updatedAt: number
}

export interface ProjectRow {
  id: string
  name: string
  description: string | null
  status: string
  conversationCount: number
  createdAt: number
  updatedAt: number
}

export interface UserPreferenceRow {
  id: string
  userId: string
  key: string
  value: string
  learnedAt: number
  confidence: number
}

export interface ImportJobRow {
  id: string
  source: string
  filePath: string
  status: string
  configJson: string
  resultJson: string | null
  error: string | null
  startedAt: number
  completedAt: number | null
}

export interface MemoryEmbeddingRow {
  id: string
  entityType: string
  entityId: string
  embedding: string
  model: string
  dimensions: number
  contentHash: string
  createdAt: number
}

// ── Filter types ────────────────────────────────────────────────────────────

export interface EntityFilter {
  type?: string
  name?: string
  limit?: number
  offset?: number
}

export interface EntityMentionFilter {
  entityId?: string
  conversationId?: string
  limit?: number
}

export interface DecisionRecordFilter {
  conversationId?: string
  limit?: number
}

export interface PatternExtractFilter {
  patternType?: string
  limit?: number
}

export interface TopicFilter {
  autoGenerated?: boolean
  limit?: number
}

export interface ProjectFilter {
  status?: string
  limit?: number
}

export interface ImportJobFilter {
  source?: string
  status?: string
  limit?: number
}

// ── Store ───────────────────────────────────────────────────────────────────

export class MemoryIntelligenceStoreImpl {
  constructor(private db: CapStoreDb) {}

  // ═══════════════════════════════════════════════════════════════════════
  // Entity
  // ═══════════════════════════════════════════════════════════════════════

  async createEntity(input: {
    name: string
    type: string
    description?: string
    confidence?: number
  }): Promise<EntityRow> {
    const now = Date.now()
    const row = await this.db.prisma.entity.create({
      data: {
        id: newId(),
        name: input.name,
        type: input.type,
        description: input.description ?? null,
        confidence: input.confidence ?? 0.5,
        mentionCount: 0,
        firstSeenAt: now,
        lastSeenAt: now,
        createdAt: now,
        updatedAt: now,
      },
    })
    return this.toEntityRow(row)
  }

  async getEntityById(id: string): Promise<EntityRow | null> {
    const row = await this.db.prisma.entity.findUnique({ where: { id } })
    return row ? this.toEntityRow(row) : null
  }

  async listEntities(filter?: EntityFilter): Promise<EntityRow[]> {
    const where: Record<string, unknown> = {}
    if (filter?.type) where.type = filter.type
    if (filter?.name) where.name = filter.name
    const rows = await this.db.prisma.entity.findMany({
      where,
      orderBy: { updatedAt: 'desc' },
      take: filter?.limit ?? 100,
      skip: filter?.offset ?? 0,
    })
    return rows.map((r) => this.toEntityRow(r))
  }

  async updateEntity(
    id: string,
    patch: Partial<Pick<EntityRow, 'name' | 'type' | 'description' | 'confidence'>>,
  ): Promise<EntityRow> {
    const now = Date.now()
    const row = await this.db.prisma.entity.update({
      where: { id },
      data: {
        ...patch,
        updatedAt: now,
      },
    })
    return this.toEntityRow(row)
  }

  async softDeleteEntity(id: string): Promise<void> {
    const now = Date.now()
    await this.db.prisma.entity.update({
      where: { id },
      data: { confidence: 0, updatedAt: now },
    })
  }

  async findByType(type: string): Promise<EntityRow[]> {
    const rows = await this.db.prisma.entity.findMany({
      where: { type },
      orderBy: { mentionCount: 'desc' },
    })
    return rows.map((r) => this.toEntityRow(r))
  }

  async findByName(name: string): Promise<EntityRow | null> {
    const row = await this.db.prisma.entity.findFirst({ where: { name } })
    return row ? this.toEntityRow(row) : null
  }

  async incrementMentionCount(id: string): Promise<void> {
    const now = Date.now()
    await this.db.prisma.entity.update({
      where: { id },
      data: {
        mentionCount: { increment: 1 },
        lastSeenAt: now,
        updatedAt: now,
      },
    })
  }

  private toEntityRow(r: any): EntityRow {
    return {
      id: r.id as string,
      name: r.name as string,
      type: r.type as string,
      description: r.description as string | null,
      confidence: r.confidence as number,
      mentionCount: r.mentionCount as number,
      firstSeenAt: Number(r.firstSeenAt),
      lastSeenAt: Number(r.lastSeenAt),
      createdAt: Number(r.createdAt),
      updatedAt: Number(r.updatedAt),
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // EntityMention
  // ═══════════════════════════════════════════════════════════════════════

  async createEntityMention(input: {
    entityId: string
    conversationId: string
    messageId: string
    context: string
    confidence?: number
  }): Promise<EntityMentionRow> {
    const now = Date.now()
    const row = await this.db.prisma.entityMention.create({
      data: {
        id: newId(),
        entityId: input.entityId,
        conversationId: input.conversationId,
        messageId: input.messageId,
        context: input.context,
        confidence: input.confidence ?? 0.5,
        ts: now,
      },
    })
    await this.incrementMentionCount(input.entityId)
    return this.toEntityMentionRow(row)
  }

  async getEntityMentionById(id: string): Promise<EntityMentionRow | null> {
    const row = await this.db.prisma.entityMention.findUnique({ where: { id } })
    return row ? this.toEntityMentionRow(row) : null
  }

  async listEntityMentions(filter?: EntityMentionFilter): Promise<EntityMentionRow[]> {
    const where: Record<string, unknown> = {}
    if (filter?.entityId) where.entityId = filter.entityId
    if (filter?.conversationId) where.conversationId = filter.conversationId
    const rows = await this.db.prisma.entityMention.findMany({
      where,
      orderBy: { ts: 'desc' },
      take: filter?.limit ?? 100,
    })
    return rows.map((r) => this.toEntityMentionRow(r))
  }

  async findByEntity(entityId: string): Promise<EntityMentionRow[]> {
    return this.listEntityMentions({ entityId, limit: 200 })
  }

  async findByConversation(conversationId: string): Promise<EntityMentionRow[]> {
    return this.listEntityMentions({ conversationId, limit: 200 })
  }

  private toEntityMentionRow(r: any): EntityMentionRow {
    return {
      id: r.id as string,
      entityId: r.entityId as string,
      conversationId: r.conversationId as string,
      messageId: r.messageId as string,
      context: r.context as string,
      confidence: r.confidence as number,
      ts: Number(r.ts),
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // DecisionRecord
  // ═══════════════════════════════════════════════════════════════════════

  async createDecisionRecord(input: {
    conversationId: string
    messageId: string
    decisionText: string
    rationale?: string
    alternatives?: string[]
    confidence?: number
  }): Promise<DecisionRecordRow> {
    const now = Date.now()
    const row = await this.db.prisma.decisionRecord.create({
      data: {
        id: newId(),
        conversationId: input.conversationId,
        messageId: input.messageId,
        decisionText: input.decisionText,
        rationale: input.rationale ?? null,
        alternativesJson: JSON.stringify(input.alternatives ?? []),
        confidence: input.confidence ?? 0.5,
        ts: now,
      },
    })
    return this.toDecisionRecordRow(row)
  }

  async getDecisionRecordById(id: string): Promise<DecisionRecordRow | null> {
    const row = await this.db.prisma.decisionRecord.findUnique({ where: { id } })
    return row ? this.toDecisionRecordRow(row) : null
  }

  async listDecisionRecords(filter?: DecisionRecordFilter): Promise<DecisionRecordRow[]> {
    const where: Record<string, unknown> = {}
    if (filter?.conversationId) where.conversationId = filter.conversationId
    const rows = await this.db.prisma.decisionRecord.findMany({
      where,
      orderBy: { ts: 'desc' },
      take: filter?.limit ?? 100,
    })
    return rows.map((r) => this.toDecisionRecordRow(r))
  }

  async updateDecisionRecord(
    id: string,
    patch: Partial<Pick<DecisionRecordRow, 'decisionText' | 'rationale' | 'confidence'>>,
  ): Promise<DecisionRecordRow> {
    const row = await this.db.prisma.decisionRecord.update({
      where: { id },
      data: patch,
    })
    return this.toDecisionRecordRow(row)
  }

  async softDeleteDecisionRecord(id: string): Promise<void> {
    await this.db.prisma.decisionRecord.update({
      where: { id },
      data: { confidence: 0 },
    })
  }

  async findByDecisionConversation(conversationId: string): Promise<DecisionRecordRow[]> {
    return this.listDecisionRecords({ conversationId, limit: 200 })
  }

  async markReversed(id: string): Promise<void> {
    await this.db.prisma.decisionRecord.update({
      where: { id },
      data: { confidence: 0, rationale: 'REVERSED' },
    })
  }

  private toDecisionRecordRow(r: any): DecisionRecordRow {
    return {
      id: r.id as string,
      conversationId: r.conversationId as string,
      messageId: r.messageId as string,
      decisionText: r.decisionText as string,
      rationale: r.rationale as string | null,
      alternativesJson: r.alternativesJson as string,
      confidence: r.confidence as number,
      ts: Number(r.ts),
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // PatternExtract
  // ═══════════════════════════════════════════════════════════════════════

  async createPatternExtract(input: {
    name: string
    description: string
    patternType: string
    confidence?: number
  }): Promise<PatternExtractRow> {
    const now = Date.now()
    const row = await this.db.prisma.patternExtract.create({
      data: {
        id: newId(),
        name: input.name,
        description: input.description,
        patternType: input.patternType,
        occurrences: 1,
        confidence: input.confidence ?? 0.5,
        firstSeenAt: now,
        lastSeenAt: now,
        createdAt: now,
        updatedAt: now,
      },
    })
    return this.toPatternExtractRow(row)
  }

  async getPatternExtractById(id: string): Promise<PatternExtractRow | null> {
    const row = await this.db.prisma.patternExtract.findUnique({ where: { id } })
    return row ? this.toPatternExtractRow(row) : null
  }

  async listPatternExtracts(filter?: PatternExtractFilter): Promise<PatternExtractRow[]> {
    const where: Record<string, unknown> = {}
    if (filter?.patternType) where.patternType = filter.patternType
    const rows = await this.db.prisma.patternExtract.findMany({
      where,
      orderBy: { occurrences: 'desc' },
      take: filter?.limit ?? 100,
    })
    return rows.map((r) => this.toPatternExtractRow(r))
  }

  async updatePatternExtract(
    id: string,
    patch: Partial<Pick<PatternExtractRow, 'name' | 'description' | 'confidence'>>,
  ): Promise<PatternExtractRow> {
    const now = Date.now()
    const row = await this.db.prisma.patternExtract.update({
      where: { id },
      data: { ...patch, updatedAt: now },
    })
    return this.toPatternExtractRow(row)
  }

  async softDeletePatternExtract(id: string): Promise<void> {
    const now = Date.now()
    await this.db.prisma.patternExtract.update({
      where: { id },
      data: { confidence: 0, updatedAt: now },
    })
  }

  async findByPatternType(patternType: string): Promise<PatternExtractRow[]> {
    return this.listPatternExtracts({ patternType, limit: 200 })
  }

  async incrementOccurrences(id: string): Promise<void> {
    const now = Date.now()
    await this.db.prisma.patternExtract.update({
      where: { id },
      data: {
        occurrences: { increment: 1 },
        lastSeenAt: now,
        updatedAt: now,
      },
    })
  }

  private toPatternExtractRow(r: any): PatternExtractRow {
    return {
      id: r.id as string,
      name: r.name as string,
      description: r.description as string,
      patternType: r.patternType as string,
      occurrences: r.occurrences as number,
      confidence: r.confidence as number,
      firstSeenAt: Number(r.firstSeenAt),
      lastSeenAt: Number(r.lastSeenAt),
      createdAt: Number(r.createdAt),
      updatedAt: Number(r.updatedAt),
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Topic
  // ═══════════════════════════════════════════════════════════════════════

  async createTopic(input: {
    name: string
    description?: string
    color?: string
  }): Promise<TopicRow> {
    const now = Date.now()
    const row = await this.db.prisma.topic.create({
      data: {
        id: newId(),
        name: input.name,
        description: input.description ?? null,
        color: input.color ?? null,
        conversationCount: 0,
        createdAt: now,
        updatedAt: now,
      },
    })
    return this.toTopicRow(row)
  }

  async getTopicById(id: string): Promise<TopicRow | null> {
    const row = await this.db.prisma.topic.findUnique({ where: { id } })
    return row ? this.toTopicRow(row) : null
  }

  async listTopics(filter?: TopicFilter): Promise<TopicRow[]> {
    const where: Record<string, unknown> = {}
    if (filter?.autoGenerated) {
      where.OR = [{ name: { startsWith: 'auto:' } }, { description: null }]
    }
    const rows = await this.db.prisma.topic.findMany({
      where,
      orderBy: { conversationCount: 'desc' },
      take: filter?.limit ?? 100,
    })
    return rows.map((r) => this.toTopicRow(r))
  }

  async updateTopic(
    id: string,
    patch: Partial<Pick<TopicRow, 'name' | 'description' | 'color'>>,
  ): Promise<TopicRow> {
    const now = Date.now()
    const row = await this.db.prisma.topic.update({
      where: { id },
      data: { ...patch, updatedAt: now },
    })
    return this.toTopicRow(row)
  }

  async softDeleteTopic(id: string): Promise<void> {
    const now = Date.now()
    await this.db.prisma.topic.update({
      where: { id },
      data: { conversationCount: 0, updatedAt: now },
    })
  }

  async findAutoGenerated(): Promise<TopicRow[]> {
    return this.listTopics({ autoGenerated: true, limit: 200 })
  }

  async assignConversation(
    conversationId: string,
    topicId: string,
    assignmentType: 'auto' | 'manual' = 'auto',
    confidence = 0.5,
  ): Promise<void> {
    const now = Date.now()
    await this.db.prisma.conversationTopic.upsert({
      where: {
        conversationId_topicId: { conversationId, topicId },
      },
      create: {
        id: newId(),
        conversationId,
        topicId,
        confidence,
        assignedAt: now,
        assignedBy: assignmentType,
      },
      update: {
        confidence,
        assignedAt: now,
        assignedBy: assignmentType,
      },
    })
    await this.db.prisma.topic.update({
      where: { id: topicId },
      data: {
        conversationCount: { increment: 1 },
        updatedAt: now,
      },
    })
  }

  private toTopicRow(r: any): TopicRow {
    return {
      id: r.id as string,
      name: r.name as string,
      description: r.description as string | null,
      color: r.color as string | null,
      conversationCount: r.conversationCount as number,
      createdAt: Number(r.createdAt),
      updatedAt: Number(r.updatedAt),
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Project
  // ═══════════════════════════════════════════════════════════════════════

  async createProject(input: {
    name: string
    description?: string
    status?: string
  }): Promise<ProjectRow> {
    const now = Date.now()
    const row = await this.db.prisma.project.create({
      data: {
        id: newId(),
        name: input.name,
        description: input.description ?? null,
        status: input.status ?? 'active',
        conversationCount: 0,
        createdAt: now,
        updatedAt: now,
      },
    })
    return this.toProjectRow(row)
  }

  async getProjectById(id: string): Promise<ProjectRow | null> {
    const row = await this.db.prisma.project.findUnique({ where: { id } })
    return row ? this.toProjectRow(row) : null
  }

  async listProjects(filter?: ProjectFilter): Promise<ProjectRow[]> {
    const where: Record<string, unknown> = {}
    if (filter?.status) where.status = filter.status
    const rows = await this.db.prisma.project.findMany({
      where,
      orderBy: { updatedAt: 'desc' },
      take: filter?.limit ?? 100,
    })
    return rows.map((r) => this.toProjectRow(r))
  }

  async updateProject(
    id: string,
    patch: Partial<Pick<ProjectRow, 'name' | 'description' | 'status'>>,
  ): Promise<ProjectRow> {
    const now = Date.now()
    const row = await this.db.prisma.project.update({
      where: { id },
      data: { ...patch, updatedAt: now },
    })
    return this.toProjectRow(row)
  }

  async softDeleteProject(id: string): Promise<void> {
    const now = Date.now()
    await this.db.prisma.project.update({
      where: { id },
      data: { status: 'deleted', updatedAt: now },
    })
  }

  async listWithConversationCounts(): Promise<Array<ProjectRow & { conversationCount: number }>> {
    return this.listProjects()
  }

  private toProjectRow(r: any): ProjectRow {
    return {
      id: r.id as string,
      name: r.name as string,
      description: r.description as string | null,
      status: r.status as string,
      conversationCount: r.conversationCount as number,
      createdAt: Number(r.createdAt),
      updatedAt: Number(r.updatedAt),
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // UserPreference
  // ═══════════════════════════════════════════════════════════════════════

  async createUserPreference(input: {
    userId: string
    key: string
    value: string
    source?: string
    confidence?: number
  }): Promise<UserPreferenceRow> {
    const now = Date.now()
    const row = await this.db.prisma.userPreference.create({
      data: {
        id: newId(),
        userId: input.userId,
        key: input.key,
        value: input.value,
        learnedAt: now,
        confidence: input.confidence ?? 0.5,
      },
    })
    return this.toUserPreferenceRow(row)
  }

  async getUserPreferenceById(id: string): Promise<UserPreferenceRow | null> {
    const row = await this.db.prisma.userPreference.findUnique({ where: { id } })
    return row ? this.toUserPreferenceRow(row) : null
  }

  async listUserPreferences(opts?: {
    userId?: string
    limit?: number
  }): Promise<UserPreferenceRow[]> {
    const where: Record<string, unknown> = {}
    if (opts?.userId) where.userId = opts.userId
    const rows = await this.db.prisma.userPreference.findMany({
      where,
      orderBy: { learnedAt: 'desc' },
      take: opts?.limit ?? 100,
    })
    return rows.map((r) => this.toUserPreferenceRow(r))
  }

  async updateUserPreference(
    id: string,
    patch: Partial<Pick<UserPreferenceRow, 'value' | 'confidence'>>,
  ): Promise<UserPreferenceRow> {
    const row = await this.db.prisma.userPreference.update({
      where: { id },
      data: patch,
    })
    return this.toUserPreferenceRow(row)
  }

  async softDeleteUserPreference(id: string): Promise<void> {
    await this.db.prisma.userPreference.update({
      where: { id },
      data: { confidence: 0 },
    })
  }

  async findByUserId(userId: string): Promise<UserPreferenceRow[]> {
    return this.listUserPreferences({ userId, limit: 200 })
  }

  async upsert(
    userId: string,
    key: string,
    value: string,
    _source = 'auto',
    confidence = 0.5,
  ): Promise<UserPreferenceRow> {
    const now = Date.now()
    const row = await this.db.prisma.userPreference.upsert({
      where: {
        userId_key: { userId, key },
      },
      create: {
        id: newId(),
        userId,
        key,
        value,
        learnedAt: now,
        confidence,
      },
      update: {
        value,
        learnedAt: now,
        confidence: Math.max(confidence, 0.5),
      },
    })
    return this.toUserPreferenceRow(row)
  }

  private toUserPreferenceRow(r: any): UserPreferenceRow {
    return {
      id: r.id as string,
      userId: r.userId as string,
      key: r.key as string,
      value: r.value as string,
      learnedAt: Number(r.learnedAt),
      confidence: r.confidence as number,
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // ImportJob
  // ═══════════════════════════════════════════════════════════════════════

  async createJob(input: {
    source: string
    filePath: string
    configJson?: string
  }): Promise<ImportJobRow> {
    const now = Date.now()
    const row = await this.db.prisma.importJob.create({
      data: {
        id: newId(),
        source: input.source,
        filePath: input.filePath,
        status: 'pending',
        configJson: input.configJson ?? '{}',
        resultJson: null,
        error: null,
        startedAt: now,
        completedAt: null,
      },
    })
    return this.toImportJobRow(row)
  }

  async getJobById(id: string): Promise<ImportJobRow | null> {
    const row = await this.db.prisma.importJob.findUnique({ where: { id } })
    return row ? this.toImportJobRow(row) : null
  }

  async listJobs(filter?: ImportJobFilter): Promise<ImportJobRow[]> {
    const where: Record<string, unknown> = {}
    if (filter?.source) where.source = filter.source
    if (filter?.status) where.status = filter.status
    const rows = await this.db.prisma.importJob.findMany({
      where,
      orderBy: { startedAt: 'desc' },
      take: filter?.limit ?? 50,
    })
    return rows.map((r) => this.toImportJobRow(r))
  }

  async updateStatus(
    id: string,
    status: string,
    result?: { resultJson?: string; error?: string },
  ): Promise<ImportJobRow> {
    const now = Date.now()
    const data: Record<string, unknown> = { status }
    if (result?.resultJson) data.resultJson = result.resultJson
    if (result?.error) data.error = result.error
    if (status === 'completed' || status === 'failed') data.completedAt = now
    const row = await this.db.prisma.importJob.update({ where: { id }, data })
    return this.toImportJobRow(row)
  }

  private toImportJobRow(r: any): ImportJobRow {
    return {
      id: r.id as string,
      source: r.source as string,
      filePath: r.filePath as string,
      status: r.status as string,
      configJson: r.configJson as string,
      resultJson: r.resultJson as string | null,
      error: r.error as string | null,
      startedAt: Number(r.startedAt),
      completedAt: r.completedAt != null ? Number(r.completedAt) : null,
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // MemoryEmbedding
  // ═══════════════════════════════════════════════════════════════════════

  async findEmbeddingByEntity(
    entityType: string,
    entityId: string,
  ): Promise<MemoryEmbeddingRow | null> {
    const row = await this.db.prisma.memoryEmbedding.findUnique({
      where: { entityType_entityId: { entityType, entityId } },
    })
    return row ? this.toMemoryEmbeddingRow(row) : null
  }

  async batchCreate(
    embeddings: Array<{
      entityType: string
      entityId: string
      embedding: string
      model: string
      dimensions: number
      contentHash: string
    }>,
  ): Promise<number> {
    let created = 0
    for (const emb of embeddings) {
      await this.db.prisma.memoryEmbedding.upsert({
        where: {
          entityType_entityId: { entityType: emb.entityType, entityId: emb.entityId },
        },
        create: {
          id: newId(),
          entityType: emb.entityType,
          entityId: emb.entityId,
          embedding: emb.embedding,
          model: emb.model,
          dimensions: emb.dimensions,
          contentHash: emb.contentHash,
          createdAt: Date.now(),
        },
        update: {
          embedding: emb.embedding,
          model: emb.model,
          dimensions: emb.dimensions,
          contentHash: emb.contentHash,
          createdAt: Date.now(),
        },
      })
      created++
    }
    return created
  }

  async deleteByEntity(entityType: string, entityId: string): Promise<void> {
    await this.db.prisma.memoryEmbedding.delete({
      where: { entityType_entityId: { entityType, entityId } },
    })
  }

  private toMemoryEmbeddingRow(r: any): MemoryEmbeddingRow {
    return {
      id: r.id as string,
      entityType: r.entityType as string,
      entityId: r.entityId as string,
      embedding: r.embedding as string,
      model: r.model as string,
      dimensions: r.dimensions as number,
      contentHash: r.contentHash as string,
      createdAt: Number(r.createdAt),
    }
  }
}
