# Regenerates docs/vivim-canvas/integration-source/*.md
# Concatenated read-only snapshot of the repo source the vivim-canvas system integrates with.
# Usage:  pwsh -NoProfile -File scripts/gen-canvas-source.ps1
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot   # repo root (scripts/ -> ..)
$out  = Join-Path $root "docs\vivim-canvas\integration-source"
New-Item -ItemType Directory -Path $out -Force | Out-Null

function Get-Lang($path) {
  switch ([System.IO.Path]::GetExtension($path)) {
    ".ts"  { "typescript" }
    ".tsx" { "tsx" }
    ".js"  { "javascript" }
    ".json"{ "json" }
    default { "text" }
  }
}

function Build-Doc($fileName, $title, $intro, $groups) {
  $sb = [System.Text.StringBuilder]::new()
  [void]$sb.AppendLine("# $title")
  [void]$sb.AppendLine("")
  [void]$sb.AppendLine("> Generated by scripts/gen-canvas-source.ps1 · Concatenated read-only snapshot of the live repo.")
  [void]$sb.AppendLine("> Purpose: give a single-file view of the source the **vivim-canvas** system")
  [void]$sb.AppendLine("> integrates with. This is a COPY for reading; the source of truth stays in-repo.")
  [void]$sb.AppendLine("")
  [void]$sb.AppendLine($intro)
  [void]$sb.AppendLine("")
  [void]$sb.AppendLine("## Contents")
  [void]$sb.AppendLine("")
  foreach ($g in $groups) {
    foreach ($f in $g.files) {
      $rel = $f -replace "\\","/"
      [void]$sb.AppendLine("- ``$rel``")
    }
  }
  [void]$sb.AppendLine("")
  [void]$sb.AppendLine("---")
  [void]$sb.AppendLine("")

  foreach ($g in $groups) {
    [void]$sb.AppendLine("## $($g.name)")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine($g.desc)
    [void]$sb.AppendLine("")
    foreach ($f in $g.files) {
      $abs = Join-Path $root $f
      $rel = $f -replace "\\","/"
      if (-not (Test-Path $abs)) { [void]$sb.AppendLine("### ``$rel`` — MISSING"); [void]$sb.AppendLine(""); continue }
      $lc = (Get-Content $abs | Measure-Object -Line).Lines
      $lang = Get-Lang $abs
      [void]$sb.AppendLine("### ``$rel``")
      [void]$sb.AppendLine("")
      [void]$sb.AppendLine("_$lc lines_")
      [void]$sb.AppendLine("")
      [void]$sb.AppendLine('```' + $lang)
      $raw = Get-Content $abs -Raw
      [void]$sb.Append($raw)
      if (-not ($raw.EndsWith("`n"))) { [void]$sb.AppendLine("") }
      [void]$sb.AppendLine('```')
      [void]$sb.AppendLine("")
    }
    [void]$sb.AppendLine("---")
    [void]$sb.AppendLine("")
  }
  $target = Join-Path $out $fileName
  [System.IO.File]::WriteAllText($target, $sb.ToString())
  $totalLines = ($sb.ToString() -split "`n").Count
  "WROTE $fileName ($totalLines md lines)"
}

# ---------- FILE 1: Capability plane ----------
$doc1 = @(
  @{ name="Unified capability registry"; desc="The agentic-native spine. Every canvas op (spawn/mutate/observe/define) registers here and auto-exports to CLI, UI, workflow, MCP, and API surfaces (Principle P5)."; files=@(
      "src/engines/unified-registry.ts",
      "src/engines/capability-bootstrap.ts") },
  @{ name="Capability engine & resolution"; desc="How capabilities are defined, resolved per provider/context, and bound. Canvas binding specs (3.4) resolve capability I/O through these."; files=@(
      "src/engines/capability.ts",
      "src/engines/capability-resolution.ts",
      "src/storage/contracts/capability-store.ts") },
  @{ name="Event bus"; desc="Typed pub/sub the canvas shell uses as its event bus (Principle P2). Layers subscribe here for cross-layer events."; files=@(
      "src/engines/capability-event-bus.ts") },
  @{ name="MCP surface"; desc="Canvas ops become MCP tools for external agents (3.13). This is the existing MCP scaffold + tool registry pattern."; files=@(
      "src/mcp/index.ts",
      "src/mcp/types.ts",
      "src/mcp/server.ts",
      "src/mcp/discovery-tools.ts") }
)
Build-Doc "01-capability-plane.md" "Canvas Integration Source — Part 1: Capability Plane" "The agentic-native spine the canvas rides on. If the canvas is the body, this is the nervous system: one plane for humans and agents." $doc1

# ---------- FILE 2: Runtime, governor & primitives ----------
$doc2 = @(
  @{ name="Kernel utilities"; desc="ID generation and the error taxonomy every canvas engine uses."; files=@(
      "src/ids.ts",
      "src/errors.ts") },
  @{ name="Live mirror bridge"; desc="The bidirectional UI<->state bridge (SOTA-01). Canvas mirror units (3.5/3.6) follow this engine's contract for optimistic updates + observation."; files=@(
      "src/engines/mirror-engine.ts") },
  @{ name="Governor Canon"; desc="The single browser I/O authority (Principle P7). Canvas layers NEVER touch CDP directly; they act only through capabilities that route here."; files=@(
      "src/engines/chrome-governor.ts") },
  @{ name="Plugin system"; desc="Existing plugin + hot-reload engines. The canvas layer registry generalizes this into frontend-as-data (P1/P3)."; files=@(
      "src/engines/plugin-system.ts",
      "src/engines/plugin-hot-reload.ts") },
  @{ name="Core primitives"; desc="Primitives the canvas composes (P6): adaptive workspace, project/topic organization, and the visual workflow engine (for 'visualize chat flows')."; files=@(
      "src/engines/adaptive-workspace.ts",
      "src/engines/conversation-organizer.ts",
      "src/engines/workflow-engine.ts",
      "src/engines/workflow-compiler.ts") }
)
Build-Doc "02-runtime-and-primitives.md" "Canvas Integration Source — Part 2: Runtime, Governor & Primitives" "The runtime bridge, the single I/O authority, the plugin substrate, and the core primitives layers are built from." $doc2

# ---------- FILE 3: Server & web shell ----------
$doc3 = @(
  @{ name="Server host"; desc="Bun server entry, WebSocket bridge, and the conversation router. The canvas WS (3.11) and canvas router (3.10) attach here."; files=@(
      "src/server/index.ts",
      "src/server/websocket.ts",
      "src/server/conversation-router.ts") },
  @{ name="Web shell (UI)"; desc="The existing React action registry + agent bridge + UI registry. The pure-HTML canvas shell replaces/absorbs this attach surface (P2)."; files=@(
      "web/ui/src/index.ts",
      "web/ui/src/actions/registry.ts",
      "web/ui/src/actions/agent-bridge.ts",
      "web/ui/src/registry/index.ts") },
  @{ name="Client SDK & store"; desc="Typed API client and the sandbox capability store — how a frontend talks to the capability plane today."; files=@(
      "web/api-client/src/index.ts",
      "web/sandbox/src/store/capability-store.ts") }
)
Build-Doc "03-server-and-web-shell.md" "Canvas Integration Source — Part 3: Server & Web Shell" "Where the canvas physically attaches: the server host, the WebSocket bridge, and the current web shell surface." $doc3

"DONE"