// scripts/manual-gen.ts
// Reflects the v10 capability registry into the user manual's Command Reference
// table (Unit 37.5). Parses cliCommand.name + mcpToolName from
// capability-bootstrap.ts and rewrites the section between the markers.

import { readFileSync, writeFileSync, existsSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { join, dirname } from "node:path"

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, "..")
const bootstrapPath = join(root, "src/engines/capability-bootstrap.ts")
const manualPath = join(root, "docs/manual/v11-user-manual.md")

interface Row {
  id: string
  cli: string
  mcp: string
}

function extractRows(): Row[] {
  const src = readFileSync(bootstrapPath, "utf8")
  const rows: Row[] = []
  // Match each makeCapability({ ... }) block's id + cliCommand.name + mcpToolName.
  const blockRe = /makeCapability\(\s*\{([\s\S]*?)\},\s*async/g
  let b: RegExpExecArray | null
  while ((b = blockRe.exec(src))) {
    const body = b[1] as string
    const id = /id:\s*'([^']+)'/.exec(body)?.[1]
    if (!id) continue
    const cli = /name:\s*'([^']+)'/.exec(body)?.[1] ?? ""
    const mcp = /mcpToolName:\s*'([^']+)'/.exec(body)?.[1] ?? ""
    rows.push({ id, cli, mcp })
  }
  return rows
}

function main() {
  const rows = extractRows()
  const table =
    "| Capability id | CLI command | MCP tool |\n|---------------|-------------|----------|\n" +
    rows.map((r) => `| \`${r.id}\` | \`${r.cli}\` | \`${r.mcp}\` |`).join("\n")

  if (!existsSync(manualPath)) {
    console.error(`Manual not found at ${manualPath}`)
    process.exit(1)
  }
  let manual = readFileSync(manualPath, "utf8")
  const start = "<!-- COMMAND_REFERENCE_START -->"
  const end = "<!-- COMMAND_REFERENCE_END -->"
  const i = manual.indexOf(start)
  const j = manual.indexOf(end)
  if (i === -1 || j === -1) {
    console.error("Command reference markers missing in manual.")
    process.exit(1)
  }
  const before = manual.slice(0, i + start.length)
  const after = manual.slice(j)
  const header = "\n_Auto-generated by `bun run docs:manual` from the capability registry._\n\n"
  const footer = "\n"
  manual = `${before}${header}${table}${footer}${after}`
  writeFileSync(manualPath, manual)
  console.log(`Inserted ${rows.length} command rows into the user manual.`)
}

main()
