// scripts/manual-gen.ts
// Reflects the v10 capability registry into the user manual's Command Reference
// table (Unit 37.5). Parses cliCommand.name + mcpToolName from
// capability-bootstrap.ts and rewrites the section between the markers.
//
// Session 2 (2026-08-07): Fixed ENOENT crash by bootstrapping the manual file
// with a minimal template (including the COMMAND_REFERENCE markers) if it
// doesn't exist yet.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { join, dirname } from "node:path"

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, "..")
const bootstrapPath = join(root, "src/engines/capability-bootstrap.ts")
const manualPath = join(root, "docs/manual/v11-user-manual.md")

interface Row {
  id: string
  cli: string
  mcp: string
}

function extractRows(): Row[] {
  const src = readFileSync(bootstrapPath, "utf8")
  const rows: Row[] = []
  // Match each makeCapability({ ... }) block's id + cliCommand.name + mcpToolName.
  const blockRe = /makeCapability\(\s*\{([\s\S]*?)\},\s*async/g
  let b: RegExpExecArray | null
  while ((b = blockRe.exec(src))) {
    const body = b[1] as string
    const id = /id:\s*'([^']+)'/.exec(body)?.[1]
    if (!id) continue
    const cli = /name:\s*'([^']+)'/.exec(body)?.[1] ?? ""
    const mcp = /mcpToolName:\s*'([^']+)'/.exec(body)?.[1] ?? ""
    rows.push({ id, cli, mcp })
  }
  return rows
}

/** Minimal manual skeleton with COMMAND_REFERENCE markers, written when missing. */
function bootstrapManual(): string {
  return `# vivim-final User Manual (v11)

> Auto-bootstrapped by \`bun run docs:manual\`. Extend the prose sections above
> and below the COMMAND_REFERENCE markers; the table itself is regenerated from
> the capability registry on each run.

## Quick start

1. Start the backend: \`bun run dev:backend\`
2. Start the frontend: \`bun run dev:frontend\`
3. Open http://localhost:3000

## Command reference

<!-- COMMAND_REFERENCE_START -->
<!-- COMMAND_REFERENCE_END -->

## See also

- [Architecture](../architecture/OVERVIEW.md)
- [API reference](../api/v11-universal-api.yaml)
- [Runbooks](../runbooks/DEV.md)
`
}

function main() {
  const rows = extractRows()
  const table =
    "| Capability id | CLI command | MCP tool |\n|---------------|-------------|----------|\n" +
    rows.map((r) => `| \`${r.id}\` | \`${r.cli}\` | \`${r.mcp}\` |`).join("\n")

  // Bootstrap the manual (and its parent dir) if missing — session 2 fix.
  const manualDir = dirname(manualPath)
  if (!existsSync(manualDir)) {
    mkdirSync(manualDir, { recursive: true })
    // [audit] removed: console.log(`Created ${manualDir}`)
  }
  if (!existsSync(manualPath)) {
    writeFileSync(manualPath, bootstrapManual())
    // [audit] removed: console.log(`Bootstrapped ${manualPath} (minimal manual skeleton).`)
  }

  let manual = readFileSync(manualPath, "utf8")
  const start = "<!-- COMMAND_REFERENCE_START -->"
  const end = "<!-- COMMAND_REFERENCE_END -->"
  let i = manual.indexOf(start)
  let j = manual.indexOf(end)
  // If markers are missing, inject them before the "## See also" section.
  if (i === -1 || j === -1) {
    const seeAlsoIdx = manual.indexOf("## See also")
    const injectAt = seeAlsoIdx === -1 ? manual.length : seeAlsoIdx
    const markers = `${start}\n${end}\n`
    manual = manual.slice(0, injectAt) + markers + manual.slice(injectAt)
    i = manual.indexOf(start)
    j = manual.indexOf(end)
  }
  const before = manual.slice(0, i + start.length)
  const after = manual.slice(j)
  const header = "\n_Auto-generated by `bun run docs:manual` from the capability registry._\n\n"
  const footer = "\n"
  manual = `${before}${header}${table}${footer}${after}`
  writeFileSync(manualPath, manual)
  // [audit] removed: console.log(`Inserted ${rows.length} command rows into the user manual.`)
}

main()
