// devops/audit-arch/report.ts
// Renders the human-readable architecture audit report markdown.

import { riskLabel, type Finding, type FindingsFile } from './findings.ts'
import type { TrendResult } from '../audit-code/findings.ts'
import { priorityLabel, type Priority, comparePriority } from './priority.ts'
import { layerOf } from './policy.ts'

const PRIORITY_ORDER: Priority[] = ['P0', 'P1', 'P2', 'P3']

export interface ArchContext {
  scope: string
  target?: string // --module prefix, if targeted
  modules: number
  edges: number
  cycles: number
  layerHistogram: { layer: number; count: number }[]
  topHubs: { module: string; fan: number }[]
}

function groupBy<T>(items: T[], key: (t: T) => string): Map<string, T[]> {
  const m = new Map<string, T[]>()
  for (const it of items) {
    const k = key(it)
    const arr = m.get(k) ?? []
    arr.push(it)
    m.set(k, arr)
  }
  return m
}

function findingBlock(f: Finding): string {
  const inv = f.invariant ? ` (${f.invariant})` : ''
  const link = f.linkedUnit ? ` | Linked: unit ${f.linkedUnit}` : ''
  const adr = f.linkedAdr ? ` / ${f.linkedAdr}` : ''
  return `### [${f.priority}] ${f.id} — ${f.title}${inv}
- **Dimension:** ${f.dimension}
- **Location:** \`${f.file}:${f.line}\`${link}${adr}
- **Evidence:** \`${f.evidence}\`
- **Impact:** ${f.impact}
- **Fix Instructions:**
  - ${f.fix.summary}
  - Steps:
${f.fix.steps.map((s) => `    - ${s}`).join('\n')}
  - Effort: ${f.fix.effort}  - Auto-fixable: ${f.fix.autoFixable ? 'yes' : 'no'}
${f.fix.patchSuggestion ? `- **Patch suggestion:**\n\`\`\`ts\n${f.fix.patchSuggestion}\n\`\`\`\n` : ''}`
}

export function renderReport(data: FindingsFile, ctx: ArchContext, trend?: TrendResult): string {
  const { run, summary, findings } = data
  const sorted = [...findings].sort(
    (a, b) => comparePriority(a.priority, b.priority) || a.id.localeCompare(b.id),
  )

  const lines: string[] = []
  const title = ctx.target ? `Architecture Audit — ${ctx.target} (${run.scope})` : `Architecture Audit — system-wide (${run.scope})`
  lines.push(`# ${title} — ${run.date}`)
  lines.push('')
  lines.push(`- **Scope:** ${run.scope}`)
  lines.push(`- **Base commit:** ${run.commit}`)
  lines.push(`- **Root:** ${run.root}`)
  lines.push(`- **Mode:** ${ctx.target ? `targeted (--module ${ctx.target})` : 'system-wide'}`)
  lines.push('')
  lines.push('## Graph Overview')
  lines.push('')
  lines.push(`- **Modules:** ${ctx.modules}`)
  lines.push(`- **Module edges:** ${ctx.edges}`)
  lines.push(`- **Cycles:** ${ctx.cycles}`)
  lines.push(`- **Layer histogram:** ${ctx.layerHistogram.map((h) => `L${h.layer}=${h.count}`).join('  ')}`)
  lines.push(`- **Top hubs:** ${ctx.topHubs.slice(0, 8).map((h) => `${h.module}(${h.fan})`).join('  ') || 'none'}`)
  lines.push('')
  lines.push('## Executive Summary')
  lines.push('')
  lines.push(`- **Risk score:** ${riskLabel(summary.risk)} (${summary.risk})`)
  lines.push(`- **Priorities:** P0: ${summary.P0}  P1: ${summary.P1}  P2: ${summary.P2}  P3: ${summary.P3}`)
  lines.push(`- **Total findings:** ${summary.total}`)
  lines.push('')
  lines.push('## Priority Legend')
  lines.push('')
  for (const p of PRIORITY_ORDER) {
    lines.push(`- **${p}** — ${priorityLabel(p)}`)
  }
  lines.push('')

  if (trend && trend.baselineDate !== 'none') {
    lines.push('## Trend (vs baseline)')
    lines.push('')
    lines.push(`- **Baseline:** ${trend.baselineDate}`)
    lines.push(`- **New:** ${trend.newFindings.length}  **Resolved:** ${trend.resolvedFindings.length}  **Unchanged:** ${trend.unchanged.length}`)
    lines.push('')
  }

  for (const p of PRIORITY_ORDER) {
    const group = sorted.filter((f) => f.priority === p)
    if (group.length === 0) continue
    lines.push(`## ${p} — ${group.length} finding(s)`)
    lines.push('')
    const byDim = groupBy(group, (f) => f.dimension)
    for (const [dim, items] of byDim) {
      lines.push(`### Dimension: ${dim}`)
      lines.push('')
      for (const f of items) lines.push(findingBlock(f))
      lines.push('')
    }
  }

  lines.push('## Fix Backlog (prioritized)')
  lines.push('')
  lines.push('| ID | P | Dimension | Location | Effort | Auto-fix |')
  lines.push('|----|---|-----------|----------|--------|----------|')
  for (const f of sorted) {
    lines.push(`| ${f.id} | ${f.priority} | ${f.dimension} | \`${f.file}:${f.line}\` | ${f.fix.effort} | ${f.fix.autoFixable ? 'yes' : 'no'} |`)
  }
  lines.push('')
  lines.push('---')
  const cmd = ctx.target ? `devops audit-arch ${run.scope} --module ${ctx.target}` : `devops audit-arch ${run.scope}`
  lines.push(`*Generated by \`bun run ${cmd}\`. Machine-readable findings: arch-findings.json*`)
  lines.push('')

  return lines.join('\n')
}

// Referenced so layerOf stays importable for callers that want layer info in
// custom report sections without an unused-import lint error.
export const _layerOf = layerOf
